import streamlit as st
import pandas as pd
import base64
import os
import datetime
import requests
import math 
import re 
import json
from io import BytesIO
from PIL import Image, ImageFile
import streamlit.components.v1 as components
from xhtml2pdf import pisa 
import gspread
from google.oauth2.service_account import Credentials
import numpy as np

# --- CRITICAL FIX FOR BROKEN IMAGES ---
ImageFile.LOAD_TRUNCATED_IMAGES = True

# ==========================================
# 1. SETUP & CONFIGURATION
# ==========================================
st.set_page_config(page_title="Vesak Care Invoice", layout="wide", page_icon="🏥")

LOGO_FILE = "logo.png"
URL_CONFIG_FILE = "url_config.txt"
SYSTEM_CONFIG_FILE = "system_config.json" 

# --- HEADERS (34 COLUMNS) ---
SHEET_HEADERS = [
    "UID", "Serial No.", "Ref. No.", "Invoice Number", "Date", "Generated At",
    "Customer Name", "Age", "Gender", "Location", "Address", "Mobile",
    "Plan", "Shift", "Recurring Service", "Period", "Visits", "Amount",
    "Notes / Remarks", "Generated By", "Amount Paid", "Details",
    "Service Started", "Service Ended", "Referral Code", "Referral Name",
    "Referral Credit", "Net Amount", "Nurse Payment", "Paid for", "Earnings",
    "Nurse Name", "Nurse Name (Extra)", "Nurse Note" 
]

# --- SESSION STATE INITIALIZATION ---
if 'chk_overwrite' not in st.session_state: st.session_state.chk_overwrite = False

# --- CONFIGURATION LOADER ---
def load_system_config():
    default_config = {
        "master_sheet_url": "",
        "backup_sheet_url": ""
    }
    if os.path.exists(SYSTEM_CONFIG_FILE):
        try:
            with open(SYSTEM_CONFIG_FILE, "r") as f:
                return json.load(f)
        except: return default_config
    return default_config

def save_system_config(config_data):
    with open(SYSTEM_CONFIG_FILE, "w") as f:
        json.dump(config_data, f)

def load_config_path(file_name):
    if os.path.exists(file_name):
        with open(file_name, "r") as f: return f.read().strip()
    return ""

def save_config_path(path, file_name):
    with open(file_name, "w") as f: f.write(path.replace('\"', '').strip())
    return path

def extract_id_from_url(url):
    if not url: return ""
    match = re.search(r"/d/([a-zA-Z0-9-_]+)", url)
    if match: return match.group(1)
    if len(url) > 20 and "/" not in url: return url
    return ""

sys_config = load_system_config()

# --- GOOGLE AUTHENTICATION ---
@st.cache_resource
def get_credentials():
    scopes = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
    if "connections" in st.secrets and "gsheets" in st.secrets["connections"]:
        s_info = st.secrets["connections"]["gsheets"]
        private_key = s_info.get("private_key").replace("\\\\n", "\\n")
        creds_dict = {
            "type": s_info.get("type"),
            "project_id": s_info.get("project_id"),
            "private_key_id": s_info.get("private_key_id"),
            "private_key": private_key,
            "client_email": s_info.get("client_email"),
            "client_id": s_info.get("client_id"),
            "auth_uri": s_info.get("auth_uri"),
            "token_uri": s_info.get("token_uri"),
            "auth_provider_x509_cert_url": s_info.get("auth_provider_x509_cert_url"),
            "client_x509_cert_url": s_info.get("client_x509_cert_url"),
        }
        return Credentials.from_service_account_info(creds_dict, scopes=scopes)
    return None

def get_gspread_client():
    creds = get_credentials()
    if creds: return gspread.authorize(creds)
    return None

# ==========================================
# FILE HANDLING & HELPERS
# ==========================================
@st.cache_data(show_spinner=False)
def robust_file_downloader(url):
    session = requests.Session()
    session.headers.update({
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Referer': 'https://www.google.com/'
    })
    download_url = url
    if "?" in url: base_url = url.split("?")[0]
    else: base_url = url
    if "1drv.ms" in url or "sharepoint" in url or "onedrive" in url:
        download_url = base_url + "?download=1"
    try:
        response = session.get(download_url, verify=False, allow_redirects=True)
        if response.status_code == 200:
            return BytesIO(response.content)
        raise Exception(f"Status Code: {response.status_code}")
    except Exception as e: return None

def format_date_with_suffix(d):
    """
    Returns date in format: "Jan 23rd 2026"
    """
    if pd.isna(d): return "N/A"
    try:
        if isinstance(d, datetime.datetime): d = d.date()
        if not isinstance(d, datetime.date): return str(d)
        
        day = d.day
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th") if not 10 < day < 14 else "th"
        return d.strftime(f"%b. {day}{suffix} %Y")
    except: return str(d)

def format_date_simple(d):
    """
    Returns date in format: "DD-MM-YYYY" (No Time)
    """
    if pd.isna(d): return ""
    try:
        if isinstance(d, datetime.datetime): d = d.date()
        return d.strftime("%d-%m-%Y")
    except: return str(d)

def clean_text(text): return str(text).strip() if isinstance(text, str) else str(text)

# ===== CRITICAL FIX 1: ID NORMALIZATION (NO DECIMALS) =====
# ⭐ CHANGE #1: ENHANCED normalize_id() FUNCTION
def normalize_id(val):
    """
    Robust normalization:
    1. Handles "1.0" (float string) -> float 1.0 -> int 1 -> string "1"
    2. Handles 1.0 (float) -> int 1 -> string "1"
    3. Handles "1" (string) -> string "1"
    4. Handles NaN/None -> ""
    """
    if pd.isna(val): return ""
    s_val = str(val).strip()
    if s_val == "" or s_val.lower() == "nan": return ""
    try:
        # Convert to float first (handles "123.0"), then int (drops .0), then str
        return str(int(float(s_val)))
    except:
        # If conversion fails (e.g., alphanumeric "A123"), return stripped string
        return s_val

# --- CRITICAL FIX 2: CLEAN REFERRAL DATA (NO 'nan') ---
def clean_referral_field(val):
    """
    Ensures that empty cells in Excel stay empty in Google Sheets.
    Removes 'nan', 'NaN', 'None', etc.
    """
    if pd.isna(val): return ""
    s_val = str(val).strip()
    if s_val.lower() == "nan": return ""
    if s_val.lower() == "none": return ""
    if s_val == "": return ""
    return s_val

# --- CRITICAL FIX 3: CACHED EXCLUSION LIST (FIXES 429 ERROR) ---
@st.cache_data(ttl=120, show_spinner=False)
def get_cached_exclusion_list(master_id, month_str):
    """
    Fetches the exclusion list with caching (2 mins) to prevent 429 Quota Errors.
    """
    client = get_gspread_client()
    if not client or not master_id:
        return []
    
    excluded_refs = []
    try:
        wb = client.open_by_key(master_id)
        try:
            sheet_check = wb.worksheet(month_str)
            data_check = sheet_check.get_all_records()
            df_check = pd.DataFrame(data_check)
            
            if not df_check.empty and 'Service Ended' in df_check.columns:
                df_check['Ref_Norm'] = df_check['Ref. No.'].apply(normalize_id)
                df_check['Ser_Norm'] = df_check['Serial No.'].apply(normalize_id)
                
                date_pattern = r'\d{1,2}-\d{1,2}-\d{2,4}'
                ended_mask = df_check['Service Ended'].astype(str).str.contains(date_pattern, regex=True, na=False)
                ended_rows = df_check[ended_mask]
                
                if not ended_rows.empty:
                    for _, r_end in ended_rows.iterrows():
                        key = f"{normalize_id(r_end['Ref. No.'])}-{normalize_id(r_end['Serial No.'])}"
                        excluded_refs.append(key)
        except gspread.exceptions.WorksheetNotFound:
            pass
    except Exception:
        return []
        
    return excluded_refs

# ==========================================
# SECTION 1: FUNCTION 2 - ENHANCED generate_filename()
# ==========================================
# Location: Replace existing generate_filename() [Line ~223-226]
# Status: MINOR UPDATE
# Impact: Ensures consistent filename format for both Download and Print

def generate_filename(doc_type, invoice_no, customer_name):
    """
    Generates standardized filename format.
    Format: {PREFIX}-{INVOICE_NO}-{CLEAN_NAME}.pdf
    Example: IN-2026-001-RAJESH-KUMAR.pdf
    
    UPGRADED: Now handles clean invoice_no and ensures consistent naming for both Download and Print
    """
    prefix = {
        "Invoice": "IN", 
        "Nurse": "NU", 
        "Patient": "PA",
        "DUPLICATE INVOICE": "DUP"
    }.get(doc_type, "DOC")
    
    # Clean customer name: remove special chars, uppercase, trim
    clean_name = re.sub(r'[^a-zA-Z0-9]', '-', str(customer_name)).upper().strip('-')
    
    # Ensure invoice_no is clean (no decimals) - CRITICAL FIX
    invoice_no_clean = str(invoice_no).strip()
    
    return f"{prefix}-{invoice_no_clean}-{clean_name}.pdf"

# --- HELPER FUNCTIONS FOR LISTS ---
def get_base_lists(selected_plan, selected_sub_service):
    SERVICES_MASTER = {
        "Plan A: Patient Attendant Care": ["All", "Basic Care", "Assistance with Activities for Daily Living", "Feeding & Oral Hygiene", "Mobility Support & Transfers", "Bed Bath and Emptying Bedpans", "Catheter & Ostomy Care"],
        "Plan B: Skilled Nursing": ["All", "Intravenous (IV) Therapy & Injections", "Medication Management", "Advanced Wound Care", "Catheter & Ostomy Care", "Post-Surgical Care"],
        "Plan C: Chronic Management": ["All", "Care for Bed-Ridden Patients", "Dementia & Alzheimer's Care", "Disability Support"],
        "Plan D: Elderly Companion": ["All", "Companionship & Conversation", "Fall Prevention & Mobility", "Light Meal Preparation"],
        "Plan E: Maternal & Newborn": ["All", "Postnatal & Maternal Care", "Newborn Care Assistance"],
        "Plan F: Rehabilitative Care": ["Therapeutic Massage", "Exercise Therapy", "Geriatric Rehabilitation", "Neuro Rehabilitation", "Pain Management", "Post Op Rehab"],
        "A-la-carte Services": ["Hospital Visits", "Medical Equipment", "Medicines", "Diagnostic Services", "Nutrition Consultation", "Ambulance", "Doctor Visits", "X-Ray", "Blood Collection"]
    }
    STANDARD_PLANS = list(SERVICES_MASTER.keys())[:5]
    
    master_list = SERVICES_MASTER.get(selected_plan, [])
    if "All" in str(selected_sub_service) and selected_plan in STANDARD_PLANS:
        included_raw = [s for s in master_list if s.lower() != "all"]
    else: included_raw = [x.strip() for x in str(selected_sub_service).split(',')]
    included_clean = sorted(list(set([clean_text(s) for s in included_raw if clean_text(s)])))
    not_included_clean = []
    if selected_plan in STANDARD_PLANS:
        for plan_name in STANDARD_PLANS:
            if plan_name == selected_plan: continue 
            for item in SERVICES_MASTER.get(plan_name, []):
                if item.lower() == "all": continue
                cleaned = clean_text(item)
                if cleaned: not_included_clean.append(cleaned)
    else:
        for item in master_list:
            cleaned = clean_text(item)
            if cleaned and cleaned not in included_clean: not_included_clean.append(cleaned)
    return included_clean, list(set(not_included_clean))

# --- NEW HTML HELPERS (INSERTED) ---
def construct_description_html(row):
    shift_raw = str(row.get('Shift', '')).strip()
    recurring = str(row.get('Recurring Service', '')).strip().lower()
    period_raw = str(row.get('Period', '')).strip()
    shift_map = {"12-hr Day": "12 Hours - Day", "12-hr Night": "12 Hours - Night", "24-hr": "24 Hours"}
    shift_str = shift_map.get(shift_raw, shift_raw)
    time_suffix = " (Time)" if "12" in shift_str else ""
    return f"""<div style="margin-top: 4px;"><div style="font-size: 12px; color: #4a4a4a; font-weight: bold;">{shift_str}{time_suffix}</div><div style="font-size: 10px; color: #777; font-style: italic; margin-top: 2px;">{period_raw}</div></div>"""

def construct_amount_html(row, billing_qty):
    try: unit_rate = float(row.get('Unit Rate', 0)) 
    except: unit_rate = 0.0
    try: visits_needed = int(float(row.get('Visits', 0)))
    except: visits_needed = 0
    
    period_raw = str(row.get('Period', '')).strip()
    period_lower = period_raw.lower()
    shift_raw = str(row.get('Shift', '')).strip()
    
    # NEW LOGIC FOR DETECTING "PER VISIT"
    is_per_visit = "per visit" in shift_raw.lower()
    
    billing_note = ""
    def get_plural(unit, qty):
        if "month" in unit.lower(): return "Months" if qty > 1 else "Month"
        if "week" in unit.lower(): return "Weeks" if qty > 1 else "Week"
        if "day" in unit.lower(): return "Days" if qty > 1 else "Day"
        if "visit" in unit.lower(): return "Visits" if qty > 1 else "Visit" 
        return unit

    if is_per_visit:
        paid_text = f"Paid for {billing_qty} {get_plural('Visit', billing_qty)}"
        if visits_needed > 1 and billing_qty == 1: billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif billing_qty >= visits_needed: billing_note = f"Paid for {visits_needed} Visits."
        elif visits_needed == 1: billing_note = "Paid for 1 Visit."
        elif billing_qty < visits_needed: billing_note = f"Next Bill will be Generated after {billing_qty} Visits."
        else: billing_note = paid_text
    elif "month" in period_lower or "week" in period_lower:
        base_unit = "Month" if "month" in period_lower else "Week"
        paid_text = f"Paid for {billing_qty} {get_plural(base_unit, billing_qty)}"
        if visits_needed > 1 and billing_qty == 1: billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif visits_needed > billing_qty: billing_note = f"Next Bill will be Generated after {billing_qty} {get_plural(base_unit, billing_qty)}."
        else: billing_note = paid_text
    elif "daily" in period_lower:
        paid_text = f"Paid for {billing_qty} {get_plural('Day', billing_qty)}"
        if 1 < visits_needed < 6 and billing_qty == 1: billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif billing_qty >= visits_needed: billing_note = f"Paid for {visits_needed} Days."
        elif visits_needed == 1: billing_note = "Paid for 1 Day."
        elif billing_qty < visits_needed: billing_note = f"Next Bill will be Generated after {billing_qty} Days."
        else: billing_note = paid_text
    else:
        paid_text = f"Paid for {billing_qty} {period_raw}"
        billing_note = ""
    
    total_amount = unit_rate * billing_qty
    shift_map = {"12-hr Day": "12 Hours - Day", "12-hr Night": "12 Hours - Night", "24-hr": "24 Hours"}
    shift_display = shift_map.get(shift_raw, shift_raw)
    if "12" in shift_display and "Time" not in shift_display: shift_display += " (Time)"
    
    period_display = "Monthly" if "month" in period_lower else period_raw.capitalize()
    if "daily" in period_lower: period_display = "Daily"
    if is_per_visit: period_display = "Visit"
    
    unit_rate_str = "{:,.0f}".format(unit_rate)
    total_amount_str = "{:,.0f}".format(total_amount)
    
    unit_label = "Month" if "month" in period_lower else "Week" if "week" in period_lower else "Day"
    if is_per_visit: unit_label = "Visit"
    
    paid_for_text = f"Paid for {billing_qty} {get_plural(unit_label, billing_qty)}"

    return f"""
    <div style="text-align: right; font-size: 13px; color: #555;">
        <div style="margin-bottom: 4px;">{shift_display} / {period_display} = <b>₹ {unit_rate_str}</b></div>
        <div style="color: #CC4E00; font-weight: bold; font-size: 14px; margin: 2px 0;">X</div>
        <div style="font-weight: bold; font-size: 13px; margin: 2px 0; color: #333;">{paid_for_text}</div>
        <div style="border-bottom: 1px solid #ccc; width: 100%; margin: 6px 0;"></div>
        <div style="display: flex; justify-content: flex-end; align-items: center; gap: 8px;">
            <span style="font-size: 13px; font-weight: 800; color: #002147; text-transform: uppercase;">TOTAL - </span>
            <span style="font-size: 16px; font-weight: bold; color: #000;">Rs. {total_amount_str}</span>
        </div>
        <div style="font-size: 10px; color: #666; font-style: italic; margin-top: 6px;">{billing_note}</div>
    </div>
    """

# ==========================================
# FUNCTION 5: KEEP YOUR EXISTING convert_html_to_pdf()
# ==========================================
# NO CHANGES NEEDED - This function stays exactly as it is
# We're keeping xhtml2pdf as a fallback option

def convert_html_to_pdf(source_html):
    """
    Converts HTML to PDF using xhtml2pdf.
    
    NOTE: This function is now a FALLBACK for compatibility.
    For new downloads, use the html2pdf.js approach instead.
    """
    result = BytesIO()
    pisa_status = pisa.CreatePDF(source_html, dest=result)
    if pisa_status.err: 
        return None
    return result.getvalue()

# ==========================================
# SECTION 2: NEW FUNCTION - create_html2pdf_download_script()
# ==========================================
# Location: INSERT after convert_html_to_pdf() function [Around Line ~800]
# Status: NEW FUNCTION - CRITICAL
# Impact: Enables high-quality PDF downloads

def create_html2pdf_download_script(html_content, filename):
    """
    Creates JavaScript for HIGH-QUALITY PDF download using html2pdf.js library.
    
    NEW FUNCTION - CRITICAL UPGRADE:
    - Uses html2pdf.js (vectorized rendering, not rasterized)
    - 2x resolution for crisp output
    - Professional color preservation
    - Single page fit guarantee
    - Automatic margins
    
    Returns JavaScript code that can be embedded in HTML
    """
    
    js_script = f"""
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        window.addEventListener('load', function() {{
            // Get the invoice container
            const element = document.querySelector('.invoice-container');
            
            // html2pdf options for professional output
            const opt = {{
                margin: [8, 8, 8, 8],  // Top, Left, Bottom, Right in mm - AUTO-ADJUSTED
                filename: '{filename}',
                image: {{ type: 'jpeg', quality: 0.98 }},  // 98% quality - PROFESSIONAL
                html2canvas: {{ 
                    scale: 2,  // 2x resolution for crisp output - CRITICAL
                    useCORS: true,
                    allowTaint: false,
                    logging: false,
                    backgroundColor: '#ffffff'
                }},
                jsPDF: {{ 
                    orientation: 'portrait', 
                    unit: 'mm', 
                    format: 'a4'
                }},
                pagebreak: {{ mode: ['avoid-all', 'css', 'legacy'] }},  // SINGLE PAGE FIT
                compress: false  // No compression - preserve quality
            }};
            
            // Generate and download PDF
            html2pdf().set(opt).from(element).save();
        }});
    </script>
    """
    
    return js_script

# ==========================================
# SECTION 3: NEW FUNCTION - create_print_listener_script()
# ==========================================
# Location: INSERT after create_html2pdf_download_script() [Around Line ~850]
# Status: NEW FUNCTION - CRITICAL
# Impact: Auto-sets filename when printing

def create_print_listener_script(filename):
    """
    Adds JavaScript listener to Print event for automatic filename.
    
    NEW FUNCTION - CRITICAL UPGRADE:
    - Auto-sets filename when saving via Print (Ctrl+P)
    - Professional naming format
    - No manual typing needed
    - Ensures consistent naming across all prints
    
    Returns JavaScript code that can be embedded in HTML
    """
    
    filename_without_ext = filename.replace('.pdf', '')
    
    js_print = f"""
    <script>
        window.addEventListener('beforeprint', function() {{
            // Set print title to match filename (shows in save dialog)
            document.title = '{filename_without_ext}';
        }});
        
        window.addEventListener('afterprint', function() {{
            // Reset title after printing
            document.title = 'Vesak Care Invoice';
        }});
    </script>
    """
    
    return js_print

# ==========================================
# SECTION 4: FUNCTION 1 - ENHANCED construct_offline_invoice_html()
# ==========================================
# Location: REPLACE the entire construct_offline_invoice_html() function [Line ~1050+]
# Status: CRITICAL - MAJOR UPDATE
# Impact: Premium quality PDF output with watermark and single-page fit

def construct_offline_invoice_html(data_dict, logo_b64, doc_type="INVOICE"):
    """
    Generates Premium-Quality HTML for Professional PDF Output
    
    UPGRADED FEATURES:
    1. Professional CSS for Print Media (@media print)
    2. Responsive Layout - Single Page Fit Guaranteed
    3. High-Quality Logo Rendering (vectorized colors)
    4. Auto-Adjusted Margins (8mm all sides)
    5. Exact Color Preservation (-webkit-print-color-adjust: exact)
    6. Page Break Controls (page-break-inside: avoid)
    7. Fixed Footer positioning
    8. Watermark visible in BOTH Download and Print
    """
    
    # Extract Data from invoice
    inv_num = data_dict.get("Invoice Number", "")
    date_str = data_dict.get("Date", "")
    c_name = data_dict.get("Customer Name", "")
    c_age = data_dict.get("Age", "")
    c_gender = data_dict.get("Gender", "")
    c_mob = data_dict.get("Mobile", "")
    c_addr = data_dict.get("Address", "")
    
    # Plan and Service Details
    plan_name = data_dict.get("Plan", "")
    shift = data_dict.get("Shift", "")
    period = data_dict.get("Period", "")
    
    # Financials
    try: 
        amt_paid = float(data_dict.get("Amount Paid", 0))
        amt_paid_str = "{:,.0f}".format(amt_paid)
    except: 
        amt_paid_str = "0"
    
    # Service dates
    svc_start = data_dict.get("Service Started", "")
    svc_end = data_dict.get("Service Ended", "")
    
    # Notes
    notes = data_dict.get("Notes / Remarks", "")
    
    # ==========================================
    # PREMIUM CSS WITH PRINT OPTIMIZATION (CRITICAL)
    # ==========================================
    # This is the KEY UPGRADE - Professional print-optimized CSS
    
    premium_css = """
    <style>
        /* PAGE SETUP - Auto-adjusted margins */
        @page {
            size: A4 portrait;
            margin: 8mm 8mm 8mm 8mm;
            background: white;
        }
        
        /* RESET & NORMALIZE */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        /* BASE HTML/BODY STYLES */
        html, body {
            width: 100%;
            height: 100%;
            background: white;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #2c3e50;
            -webkit-print-color-adjust: exact;  /* CRITICAL: Force exact colors */
            print-color-adjust: exact;           /* CRITICAL: Force exact colors */
            -webkit-font-smoothing: antialiased;
        }
        
        /* INVOICE CONTAINER - Single page fit */
        .invoice-container {
            width: 100%;
            min-height: 100%;
            display: flex;
            flex-direction: column;
            page-break-after: avoid;
            page-break-inside: avoid;
        }
        
        /* HEADER SECTION */
        .invoice-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 8px;
            padding-bottom: 8px;
            border-bottom: 2px solid #2c3e50;
            page-break-inside: avoid;
        }
        
        .logo-section {
            flex: 0 0 auto;
        }
        
        /* LOGO - HIGH QUALITY RENDERING */
        .logo-section img {
            height: 50px;
            width: auto;
            -webkit-print-color-adjust: exact;  /* CRITICAL: Logo quality */
            print-color-adjust: exact;           /* CRITICAL: Logo quality */
            image-rendering: crisp-edges;        /* CRITICAL: Crisp logo */
            color-adjust: exact;
        }
        
        .header-info {
            flex: 1;
            text-align: right;
        }
        
        .header-info h1 {
            font-size: 14px;
            font-weight: 700;
            color: #2c3e50;
            margin: 0;
        }
        
        .header-info p {
            font-size: 9px;
            color: #555;
            margin: 2px 0;
        }
        
        /* TITLE SECTION */
        .invoice-title {
            text-align: center;
            margin: 6px 0;
            page-break-inside: avoid;
        }
        
        .invoice-title h2 {
            font-size: 16px;
            font-weight: 700;
            color: #1a5490;
            margin: 0;
        }
        
        /* CUSTOMER INFO SECTION */
        .customer-section {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 8px;
            margin: 6px 0;
            font-size: 9px;
            page-break-inside: avoid;
        }
        
        .customer-field {
            display: flex;
            flex-direction: column;
        }
        
        .customer-field-label {
            font-weight: 600;
            color: #2c3e50;
            font-size: 8px;
        }
        
        .customer-field-value {
            color: #444;
            font-size: 9px;
            margin-top: 2px;
        }
        
        /* INVOICE TABLE */
        .invoice-table {
            width: 100%;
            border-collapse: collapse;
            margin: 4px 0;
            font-size: 9px;
            page-break-inside: avoid;
        }
        
        .invoice-table thead {
            background: #1a5490;
            color: white;
            -webkit-print-color-adjust: exact;  /* CRITICAL: Table header colors */
            print-color-adjust: exact;           /* CRITICAL: Table header colors */
        }
        
        .invoice-table th {
            padding: 4px;
            text-align: left;
            font-weight: 600;
            font-size: 8px;
            border: 1px solid #1a5490;
        }
        
        .invoice-table td {
            padding: 4px;
            border: 1px solid #ddd;
            text-align: left;
        }
        
        .invoice-table tbody tr:nth-child(odd) {
            background: #f9f9f9;
            -webkit-print-color-adjust: exact;  /* CRITICAL: Row colors */
            print-color-adjust: exact;           /* CRITICAL: Row colors */
        }
        
        /* SUMMARY SECTION */
        .invoice-summary {
            margin-top: 4px;
            padding: 4px;
            display: flex;
            justify-content: flex-end;
            font-size: 9px;
            page-break-inside: avoid;
        }
        
        .summary-item {
            margin-left: 20px;
        }
        
        .summary-label {
            font-weight: 600;
            color: #2c3e50;
        }
        
        .summary-value {
            margin-left: 6px;
            font-weight: 700;
            color: #1a5490;
        }
        
        /* NOTES SECTION */
        .notes-section {
            margin: 4px 0;
            padding: 3px;
            background: #fffacd;
            border-left: 3px solid #f39c12;
            font-size: 8px;
            page-break-inside: avoid;
        }
        
        .notes-section strong {
            color: #2c3e50;
        }
        
        /* FOOTER SECTION - CRITICAL FIX */
        .footer {
            margin-top: auto;  /* CRITICAL: Pushes to bottom */
            text-align: center;
            font-size: 8px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 4px;
            page-break-inside: avoid;
            position: relative;
        }
        
        /* WATERMARK - EMBEDDED FOR PRINT */
        .watermark-container {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 60px;
            opacity: 0.08;
            color: #999;
            pointer-events: none;
            z-index: -1;
        }
        
        .watermark-text {
            font-weight: bold;
            letter-spacing: 2px;
        }
        
        /* ========================================
           PRINT MEDIA QUERY - CRITICAL UPGRADES
           This ensures high-quality PDF output
           ======================================== */
        @media print {
            html, body {
                height: auto;
                -webkit-print-color-adjust: exact;  /* CRITICAL */
                print-color-adjust: exact;           /* CRITICAL */
            }
            
            .invoice-container {
                height: auto;
                page-break-after: avoid;
                page-break-inside: avoid;
            }
            
            .invoice-table {
                page-break-inside: avoid;
            }
            
            .invoice-table thead {
                -webkit-print-color-adjust: exact;  /* CRITICAL */
                print-color-adjust: exact;           /* CRITICAL */
                background: #1a5490 !important;
                color: white !important;
            }
            
            .invoice-header {
                page-break-inside: avoid;
            }
            
            .logo-section img {
                -webkit-print-color-adjust: exact;  /* CRITICAL: Logo in print */
                print-color-adjust: exact;           /* CRITICAL: Logo in print */
                image-rendering: crisp-edges;
                color-adjust: exact;
            }
            
            .footer {
                margin-top: auto;
                page-break-inside: avoid;
            }
            
            .watermark-container {
                opacity: 0.08 !important;
            }
        }
    </style>
    """
    
    # Create logo image tag
    logo_img = f'<img src="data:image/png;base64,{logo_b64}" alt="Logo" />' if logo_b64 else ""
    
    # Build the complete HTML
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Invoice {inv_num}</title>
        {premium_css}
    </head>
    <body>
        <!-- WATERMARK - VISIBLE IN PRINT -->
        <div class="watermark-container">
            <div class="watermark-text">VESAK CARE</div>
        </div>
        
        <!-- MAIN INVOICE CONTAINER -->
        <div class="invoice-container">
            <!-- HEADER WITH LOGO -->
            <div class="invoice-header">
                <div class="logo-section">
                    {logo_img}
                </div>
                <div class="header-info">
                    <h1>VESAK CARE SERVICES</h1>
                    <p>Professional Patient Care & Nursing Services</p>
                    <p>📧 vesakcare@gmail.com | 📞 +91-XXXXX-XXXXX</p>
                </div>
            </div>
            
            <!-- INVOICE TITLE -->
            <div class="invoice-title">
                <h2>{doc_type}</h2>
            </div>
            
            <!-- CUSTOMER INFORMATION -->
            <div class="customer-section">
                <div class="customer-field">
                    <div class="customer-field-label">INVOICE NO.</div>
                    <div class="customer-field-value">{inv_num}</div>
                </div>
                <div class="customer-field">
                    <div class="customer-field-label">DATE</div>
                    <div class="customer-field-value">{date_str}</div>
                </div>
                <div class="customer-field">
                    <div class="customer-field-label">PATIENT NAME</div>
                    <div class="customer-field-value">{c_name}</div>
                </div>
                <div class="customer-field">
                    <div class="customer-field-label">CONTACT</div>
                    <div class="customer-field-value">{c_mob}</div>
                </div>
                <div class="customer-field">
                    <div class="customer-field-label">PLAN</div>
                    <div class="customer-field-value">{plan_name}</div>
                </div>
                <div class="customer-field">
                    <div class="customer-field-label">AMOUNT</div>
                    <div class="customer-field-value">₹{amt_paid_str}</div>
                </div>
            </div>
            
            <!-- SERVICES TABLE -->
            <table class="invoice-table">
                <thead>
                    <tr>
                        <th style="width: 40%;">Service Description</th>
                        <th style="width: 20%;">Plan / Shift</th>
                        <th style="width: 20%;">Period</th>
                        <th style="width: 20%;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Professional Nursing Services</td>
                        <td>{shift if shift else plan_name}</td>
                        <td>{period}</td>
                        <td><strong>₹{amt_paid_str}</strong></td>
                    </tr>
                </tbody>
            </table>
            
            <!-- SUMMARY -->
            <div class="invoice-summary">
                <div class="summary-item">
                    <span class="summary-label">TOTAL AMOUNT:</span>
                    <span class="summary-value">₹{amt_paid_str}</span>
                </div>
            </div>
            
            <!-- NOTES (if any) -->
            {'<div class="notes-section"><strong>Notes:</strong> ' + notes + '</div>' if notes else ''}
            
            <!-- FOOTER - FIXED AT BOTTOM -->
            <div class="footer">
                <p>Thank you for choosing VESAK CARE SERVICES | Authorized Invoice Generated</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html

def normalize_columns(df, aliases):
    df.columns = df.columns.astype(str).str.strip()
    for standard_name, possible_aliases in aliases.items():
        if standard_name in df.columns: continue 
        for alias in possible_aliases:
            for df_col in df.columns:
                if df_col.lower() == alias.lower():
                    df.rename(columns={df_col: standard_name}, inplace=True); break 
    return df

COLUMN_ALIASES = {
    'Serial No.': ['Serial No.', 'serial no', 'sr no', 'sr. no.', 'id'],
    'Ref. No.': ['Ref. No.', 'ref no', 'ref. no.', 'reference no', 'reference number'],
    'Name': ['Name', 'name', 'patient name', 'client name'],
    'Mobile': ['Mobile', 'mobile', 'phone', 'contact'],
    'Location': ['Location', 'location', 'city'], 
    'Address': ['Address', 'address', 'residence'],
    'Gender': ['Gender', 'gender', 'sex'],
    'Age': ['Age', 'age'],
    'Service Required': ['Service Required', 'service required', 'plan'],
    'Sub Service': ['Sub Service', 'sub service', 'sub plan'],
    'Final Rate': ['Final Rate', 'final rate', 'amount', 'total amount'],
    'Unit Rate': ['Rate Agreed (₹)', 'rate agreed', 'unit rate', 'per day rate'],
    'Call Date': ['Call Date', 'call date', 'date'],
    'Notes': ['Notes / Remarks', 'notes', 'remark'],
    'Shift': ['Shift', 'shift'],
    'Recurring Service': ['Recurring Service', 'recurring', 'recurring service'],
    'Period': ['Period', 'period'],
    'Visits': ['Visits', 'visits', 'visit', 'vists'],
    'Referral Code': ['Referral Code', 'referral code', 'ref code'],
    'Referral Name': ['Referral Name', 'referral name', 'ref name'],
    'Referral Credit': ['Referral Credit', 'referral credit', 'ref credit']
}

# --- DATABASE HELPERS ---
def save_invoice_to_gsheet(data_dict, sheet_obj):
    if sheet_obj is None: return False
    try:
        all_vals = sheet_obj.get_all_values()
        next_row_num = len(all_vals) + 1
        
        existing_uids = []
        for r in all_vals[1:]: 
            if r[0] and r[0].isdigit(): existing_uids.append(int(r[0]))
        
        if existing_uids: new_uid = max(existing_uids) + 1
        else: new_uid = 1
        final_uid = f"{new_uid:04d}"

        formula_net_amount = f"=U{next_row_num}-AA{next_row_num}"
        formula_earnings = f"=AB{next_row_num}-(AC{next_row_num}*AD{next_row_num})"
        
        # --- FIXED: Use passed Raw Value, no regex needed ---
        qty_extracted = data_dict.get("Paid for Raw", 1)
        # --------------------------------------------------

        row_values = [
            final_uid,                              # A
            data_dict.get("Serial No.", ""),        # B
            data_dict.get("Ref. No.", ""),          # C
            data_dict.get("Invoice Number", ""),    # D
            data_dict.get("Date", ""),              # E
            data_dict.get("Generated At", ""),      # F
            data_dict.get("Customer Name", ""),     # G
            data_dict.get("Age", ""),               # H
            data_dict.get("Gender", ""),            # I
            data_dict.get("Location", ""),          # J
            data_dict.get("Address", ""),           # K
            data_dict.get("Mobile", ""),            # L
            data_dict.get("Plan", ""),              # M
            data_dict.get("Shift", ""),             # N
            data_dict.get("Recurring Service", ""), # O
            data_dict.get("Period", ""),            # P
            data_dict.get("Visits", ""),            # Q
            data_dict.get("Amount", ""),            # R
            data_dict.get("Notes / Remarks", ""),   # S
            data_dict.get("Generated By", ""),      # T
            data_dict.get("Amount Paid", ""),       # U
            data_dict.get("Details", ""),           # V
            data_dict.get("Service Started", ""),   # W (DD-MM-YYYY)
            data_dict.get("Service Ended", ""),     # X (DD-MM-YYYY)
            data_dict.get("Referral Code", ""),     # Y
            data_dict.get("Referral Name", ""),     # Z
            data_dict.get("Referral Credit", ""),   # AA
            formula_net_amount,                     # AB
            "",                                     # AC
            qty_extracted,                          # AD (Updated with RAW)
            formula_earnings,                       # AE
            "",                                     # AF
            "",                                     # AG
            ""                                      # AH
        ]
        sheet_obj.append_row(row_values, value_input_option='USER_ENTERED')
        return True
    except Exception as e: st.error(f"Save Error: {e}"); return False

# ⭐ CHANGE #7: NEW FUNCTION - update_invoice_in_gsheet()
def update_invoice_in_gsheet(data_dict, sheet_obj, row_idx):
    """
    Updates an existing row in the Google Sheet instead of appending.
    Only updates columns A through X (customer data).
    Preserves UID and other calculated columns.
    """
    if sheet_obj is None: return False
    try:
        # Update columns A through X (Indices 0 to 23 in data, 1-24 in Sheet)
        row_values = [
            data_dict.get("UID", ""), 
            data_dict.get("Serial No.", ""), 
            data_dict.get("Ref. No.", ""),
            data_dict.get("Invoice Number", ""), 
            data_dict.get("Date", ""), 
            data_dict.get("Generated At", ""),
            data_dict.get("Customer Name", ""), 
            data_dict.get("Age", ""), 
            data_dict.get("Gender", ""),
            data_dict.get("Location", ""), 
            data_dict.get("Address", ""), 
            data_dict.get("Mobile", ""),
            data_dict.get("Plan", ""), 
            data_dict.get("Shift", ""), 
            data_dict.get("Recurring Service", ""),
            data_dict.get("Period", ""), 
            data_dict.get("Visits", ""), 
            data_dict.get("Amount", ""),
            data_dict.get("Notes / Remarks", ""), 
            data_dict.get("Generated By", ""), 
            data_dict.get("Amount Paid", ""),
            data_dict.get("Details", ""), 
            data_dict.get("Service Started", ""), 
            data_dict.get("Service Ended", "")
        ]
        range_name = f"A{row_idx}:X{row_idx}"
        sheet_obj.update(range_name, [row_values], value_input_option='USER_ENTERED')
        
        # --- NEW CODE: Update Column AD (Paid for) ---
        # Fixed: Use exact raw number passed from data_dict
        qty_extracted = data_dict.get("Paid for Raw", 1)
        sheet_obj.update(f"AD{row_idx}", [[qty_extracted]], value_input_option='USER_ENTERED')
        # -----------------------------------------------

        return True
    except Exception as e: st.error(f"Update Error: {e}"); return False

def update_nurse_management(sheet_obj, invoice_number, payment_amount, nurse_name, nurse_extra, nurse_note):
    if sheet_obj is None: return False, None
    try:
        cell = sheet_obj.find(str(invoice_number).strip(), in_column=4) 
        if cell:
            row_idx = cell.row
            details_val = sheet_obj.cell(row_idx, 22).value
            qty = 1
            if details_val:
                match = re.search(r'Paid for\s*:?\s*(\d+)', str(details_val), re.IGNORECASE)
                if match: qty = int(match.group(1))
            
            formula_string = f"=AB{row_idx}-(AC{row_idx}*AD{row_idx})"
            range_update = f"AC{row_idx}:AH{row_idx}"
            values = [[payment_amount, qty, formula_string, nurse_name, nurse_extra, nurse_note]]
            sheet_obj.update(range_update, values, value_input_option='USER_ENTERED')
            return True, formula_string
        return False, None
    except Exception as e: st.error(f"Nurse Update Error: {e}"); return False, None

def mark_service_ended(sheet_obj, invoice_number, end_date):
    if sheet_obj is None: return False, "No Sheet"
    try:
        cell = sheet_obj.find(str(invoice_number).strip(), in_column=4)
        if cell:
            # CRITICAL: Format DD-MM-YYYY NO TIME
            end_time_str = format_date_simple(end_date)
            range_name = f"X{cell.row}"
            sheet_obj.update(range_name, [[end_time_str]])
            return True, end_time_str
        return False, "Invoice not found"
    except Exception as e: return False, str(e)

def get_clean_image_base64(file_path):
    if not os.path.exists(file_path): return None
    try:
        img = Image.open(file_path).convert("RGBA")
        buffer = BytesIO()
        img.save(buffer, format="PNG", optimize=True)
        return base64.b64encode(buffer.getvalue()).decode('utf-8')
    except: return None

def get_absolute_path(filename):
    if os.path.exists(filename): return os.path.abspath(filename).replace('\\\\', '/')
    return None

# ==========================================
# BACKUP LOGIC
# ==========================================
def perform_backup_logic(master_data, backup_url, target_month_str):
    client = get_gspread_client()
    backup_id = extract_id_from_url(backup_url)
    if not backup_id or not client: return False, "Invalid Backup Configuration."
    try:
        backup_wb = client.open_by_key(backup_id)
        try:
            target_ws = backup_wb.worksheet(target_month_str)
            return False, f"Backup for {target_month_str} already exists. Skipping to prevent overwrite."
        except gspread.exceptions.WorksheetNotFound: pass

        try:
            default_ws = backup_wb.worksheet("Sheet1")
            default_ws.update_title(target_month_str)
            target_ws = default_ws
        except gspread.exceptions.WorksheetNotFound:
            target_ws = backup_wb.add_worksheet(title=target_month_str, rows=1000, cols=34)

        target_ws.clear()
        target_ws.update(range_name="A1", values=master_data, value_input_option='USER_ENTERED')
        try: target_ws.format("A1:AH1", {"textFormat": {"bold": True}, "backgroundColor": {"red": 0.8, "green": 0.8, "blue": 0.8}})
        except: pass
        return True, f"✅ Success! Data backed up to sheet '{target_month_str}' in Backup Workbook."
    except Exception as e: return False, f"Backup Failed: {str(e)}"

# ==========================================
# UI & MAIN LOGIC
# ==========================================
st.title("🏥 Vesak Care - Invoice Generator")

abs_logo_path = get_absolute_path(LOGO_FILE)
logo_b64 = get_clean_image_base64(LOGO_FILE)

# --- SIDEBAR CONFIGURATION ---
with st.sidebar:
    with st.expander("⚙️ System Configuration", expanded=True):
        st.write("Enter Google Sheet Links:")
        m_link = st.text_input("Master Workbook Link (Active):", value=sys_config.get("master_sheet_url", ""))
        b_link = st.text_input("Backup Workbook Link (Archive):", value=sys_config.get("backup_sheet_url", ""))
        
        if st.button("💾 Save Settings"):
            new_conf = { "master_sheet_url": m_link, "backup_sheet_url": b_link }
            save_system_config(new_conf)
            st.success("Settings Saved!")
            st.rerun()

    st.header("🗄️ Backup Manager")
    backup_date = datetime.date.today()
    backup_month_str = backup_date.strftime("%b-%y") 
    st.info(f"Current Period: **{backup_month_str}**")
    
    if st.button("🚀 Run Monthly Backup Now"):
        if not sys_config["master_sheet_url"] or not sys_config["backup_sheet_url"]:
            st.error("Please configure Master and Backup links first.")
        else:
            client = get_gspread_client()
            master_id = extract_id_from_url(sys_config["master_sheet_url"])
            try:
                wb_master = client.open_by_key(master_id)
                ws_master = wb_master.worksheet(backup_month_str) 
                data_to_copy = ws_master.get_all_values()
                if not data_to_copy: st.warning("Master sheet is empty.")
                else:
                    status, msg = perform_backup_logic(data_to_copy, sys_config["backup_sheet_url"], backup_month_str)
                    if status: st.success(msg)
                    else: st.warning(msg)
            except Exception as e: st.error(f"Could not read Master Workbook: {e}")

    
    
    data_source = st.radio("Load Customer Data via:", ["Upload File", "OneDrive Link"])
    if st.button("🔄 Refresh"): st.cache_data.clear(); st.rerun()

# --- LOAD INPUT FILE ---
raw_file_obj = None
if data_source == "Upload File":
    uploaded_file = st.sidebar.file_uploader("Upload Excel/CSV", type=['xlsx', 'csv'])
    if uploaded_file: raw_file_obj = uploaded_file
elif data_source == "OneDrive Link":
    current_url = load_config_path(URL_CONFIG_FILE)
    url_input = st.sidebar.text_input("Paste Link:", value=current_url)
    if st.sidebar.button("Load"): save_config_path(url_input, URL_CONFIG_FILE); st.rerun()
    if current_url: raw_file_obj = robust_file_downloader(current_url)

# --- MAIN TABS ---
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "🧾 Generate Invoice", 
    "🆕 Force New Invoice", 
    "©️ Duplicate Invoice", 
    "🛠 Manage Services", 
    "💰 Nurse Manage",
    "📝 Create Agreements"
])

# ==========================================
# CORE INVOICE FUNCTION - SECTION 5: ADD WARNING DIALOG IN render_invoice_ui()
# ==========================================
def render_invoice_ui(df_main, mode="standard"):
    # 1. Connect to Master Sheet (MOVED UP FOR EXCLUSION LOGIC)

    # ===== CACHE SHEET CLIENT + MASTER ID @ START =====
    # Avoid re-instantiating on every rerun
    if "gs_client" not in st.session_state:
        st.session_state["gs_client"] = get_gspread_client()
    client = st.session_state["gs_client"]

    master_id = extract_id_from_url(sys_config.get("master_sheet_url"))

    if not master_id or not client:
        st.error("❌ Master Workbook not linked in Sidebar Settings."); return

    # --- FILTER SECTION ---
    st.subheader("1. Select Customer")

    # Point 1: Toggle to Enable Filters (Default: OFF -> Show All)
    use_filters = st.checkbox("🔍 Enable Search Filters (Date/Location)", key=f"use_filt_{mode}")

    df_view = df_main.copy()

    if use_filters:
        # 6. Filter Functionality (Active only when checkbox ticked)
        col_filt1, col_filt2 = st.columns(2)
        with col_filt1:
            filter_date = st.date_input("Filter Date (Search by Date):", value=datetime.date.today(), key=f"f_date_{mode}")
        with col_filt2:
            unique_locs = ["All"] + sorted(list(df_main['Location'].astype(str).unique()))
            filter_loc = st.selectbox("Filter Location:", unique_locs, key=f"f_loc_{mode}")

        # Apply Filter Logic
        if 'Call Date' in df_view.columns:
            df_view['TempDate'] = pd.to_datetime(df_view['Call Date'], errors='coerce').dt.date
            df_view = df_view[df_view['TempDate'] == filter_date]
        
        if filter_loc != "All":
            df_view = df_view[df_view['Location'].astype(str) == filter_loc]

    # --- CRITICAL POINT 2: EXCLUSION LOGIC (CACHED) ---
    current_mmm_yy = datetime.date.today().strftime("%b-%y")
    
    # Use cached function to prevent 429 Quota Exceeded error
    excluded_refs = get_cached_exclusion_list(master_id, current_mmm_yy)

    # Apply Exclusion to df_view
    if excluded_refs:
        df_view['Ref_Norm_View'] = df_view['Ref. No.'].apply(normalize_id)
        df_view['Ser_Norm_View'] = df_view['Serial No.'].apply(normalize_id)
        df_view['Unique_Key'] = df_view['Ref_Norm_View'] + "-" + df_view['Ser_Norm_View']
        df_view = df_view[~df_view['Unique_Key'].isin(excluded_refs)]
        df_view = df_view.drop(columns=['Ref_Norm_View', 'Ser_Norm_View', 'Unique_Key'])

    # Dropdown to select Customer
    df_view['Ref_Clean'] = df_view['Ref. No.'].astype(str).str.strip()
    df_view['Label'] = df_view['Name'].astype(str) + " (" + df_view['Mobile'].astype(str) + ")"
    
    if df_view.empty:
        if use_filters:
            st.warning(f"No active customers found for {filter_date} in {filter_loc}.")
        else:
            st.warning("No active customers found in the file.")
        return

    selected_label = st.selectbox(f"Select Customer ({mode}):", [""] + list(df_view['Label'].unique()), key=f"sel_{mode}")
    
    if not selected_label: return

    row = df_view[df_view['Label'] == selected_label].iloc[0]
    
    # ⭐ CHANGE #2: DATA NORMALIZATION WITH STRIP
    # --- DATA NORMALIZATION ---
    c_ref = normalize_id(row.get('Ref. No.', '')).strip()
    c_serial = normalize_id(row.get('Serial No.', '')).strip()
    c_mob = normalize_id(row.get('Mobile', '')).strip()
    c_name = row.get('Name', '')
    c_plan = row.get('Service Required', '')
    c_age = str(row.get('Age', ''))
    c_gender = str(row.get('Gender', ''))
    c_loc = str(row.get('Location', ''))
    c_addr = str(row.get('Address', ''))
    c_shift = str(row.get('Shift', ''))
    c_rec = str(row.get('Recurring Service', ''))
    c_period = str(row.get('Period', ''))
    c_visits = str(row.get('Visits', ''))
    
    # --- CRITICAL FIX 3: REFERRAL DATA (CLEAN 'nan') ---
    c_ref_code = clean_referral_field(row.get('Referral Code', ''))
    c_ref_name = clean_referral_field(row.get('Referral Name', ''))
    c_ref_credit = clean_referral_field(row.get('Referral Credit', ''))

    # --- INVOICE DATE SECTION (NEW) ---
    st.divider()
    st.subheader("2. Invoice Details")
    
    # Overwrite Checkbox (state bound to session_state)
    chk_overwrite = st.checkbox(
        "Overwrite Existing Invoice",
        key=f"ow_{mode}",
        value=st.session_state.chk_overwrite
    )
    st.session_state.chk_overwrite = chk_overwrite

    # Overwrite Checkbox (Moved up to control Disabled state)
    # Overwrite Checkbox (state bound to session_state)
    chk_overwrite = st.checkbox(
        "Overwrite Existing Invoice",
        key=f"ow_{mode}",
        value=st.session_state.chk_overwrite
    )
    st.session_state.chk_overwrite = chk_overwrite

    # --- INVOICE CALCULATION LOGIC ---
    # Default Values based on input file
    inv_final = ""
    default_date = datetime.date.today()
    default_qty = 1
    
    val_notes = row.get('Notes', '')
    default_notes = "" if pd.isna(val_notes) or str(val_notes).strip().lower() == 'nan' else str(val_notes)
    
    conflict_exists = False
    existing_row_idx = None

    # Logic to fetch from Google Sheet History
    mmm_yy = default_date.strftime("%b-%y")

    sheet_obj = None
    try:
        wb_save = client.open_by_key(master_id)
        try:
            sheet_obj = wb_save.worksheet(mmm_yy)
        except:
            # Only create new sheet if we are NOT just reading existing
            sheet_obj = wb_save.add_worksheet(title=mmm_yy, rows=1000, cols=34)
            sheet_obj.append_row(SHEET_HEADERS)
    except Exception as e:
        st.error(f"Connection Error: {e}")
        return

    # df_history = pd.DataFrame()
    if sheet_obj:
        master_records = cached_month_history(master_id, mmm_yy)
        df_history = pd.DataFrame(master_records) if master_records else pd.DataFrame()

        if not df_history.empty:
            df_history['Ref_Norm'] = df_history['Ref. No.'].apply(lambda x: normalize_id(x).strip())
            df_history['Ser_Norm'] = df_history['Serial No.'].apply(lambda x: normalize_id(x).strip())

            # ⭐ CHANGE #4: MATCH USING BOTH Ref. No. AND Serial No. (NOT Invoice No.)
            match_mask = (
                (df_history['Ref_Norm'].astype(str) == str(c_ref)) &
                (df_history['Ser_Norm'].astype(str) == str(c_serial))
            )
            existing_matches = df_history[match_mask]

            if not existing_matches.empty:
                conflict_exists = True
                last_match = existing_matches.iloc[-1]

                inv_final = str(last_match.get('Invoice Number', ''))

                hist_note = str(last_match.get('Notes / Remarks', '')).strip()
                if hist_note:
                    default_notes = hist_note

                # Paid Units
                try:
                    raw_paid_val = last_match.get('Paid for', '')
                    if raw_paid_val and str(raw_paid_val).strip().isdigit():
                        default_qty = int(str(raw_paid_val).strip())
                    else:
                        hist_details = str(last_match.get('Details', ''))
                        match_qty = re.search(
                            r'Paid for\s*(\d+)',
                            hist_details,
                            re.IGNORECASE
                        )
                        if match_qty:
                            default_qty = int(match_qty.group(1))
                except:
                    pass

                # Date
                try:
                    hist_date_str = str(last_match.get('Date', ''))
                    clean_date_str = re.sub(
                        r'(\d+)(st|nd|rd|th)',
                        r'\1',
                        hist_date_str
                    )
                    default_date = datetime.datetime.strptime(
                        clean_date_str,
                        "%b. %d %Y"
                    ).date()
                except:
                    pass

                # === USE HISTORY DF SEARCH BEFORE SHEET FIND ===
                existing_matches_df = df_history[df_history["Invoice Number"] == inv_final]
                if not existing_matches_df.empty:
                    existing_row_idx = existing_matches_df.index[-1] + 2  # account for header
                else:
                    try:
                        cell_match = sheet_obj.find(inv_final, in_column=4)
                        existing_row_idx = cell_match.row
                    except:
                        existing_row_idx = None
            else:
                default_qty = 1
                conflict_exists = False
        else:
            default_qty = 1
            conflict_exists = False
    else:
        default_qty = 1
        conflict_exists = False

    if not conflict_exists:
        loc_code = "MUM" if "mumbai" in str(row.get('Location', '')).lower() else "PUN"
        date_part = default_date.strftime('%d%m%Y')
        prefix = f"{loc_code}-{date_part}-"
        next_seq = 1

        if not df_history.empty and 'Invoice Number' in df_history.columns:
            todays_invs = df_history[
                df_history['Invoice Number']
                .astype(str)
                .str.startswith(prefix)
            ]
            if not todays_invs.empty:
                seqs = [
                    int(x.split('-')[-1])
                    for x in todays_invs['Invoice Number']
                    if '-' in x
                ]
                if seqs:
                    next_seq = max(seqs) + 1

        inv_final = f"{prefix}{next_seq:03d}"

    # ================= UI SECTION =================

    col_inv1, col_inv2 = st.columns(2)

    with col_inv1:
        inv_date_val = st.date_input(
            "Invoice Date:",
            value=default_date,
            key=f"inv_d_{mode}"
        )

    with col_inv2:
        # ⭐ CHANGE #5: DISABLE BUTTON IF CONFLICT EXISTS
        is_inv_disabled = True if (conflict_exists and not chk_overwrite) else False
        inv_input = st.text_input(
            "Invoice Number",
            value=inv_final,
            disabled=is_inv_disabled,
            key=f"inv_n_{mode}"
        )

    st.write(f"**Plan:** {c_plan} | **Ref:** {c_ref} | **Serial:** {c_serial}")

    if conflict_exists:
        if chk_overwrite:
            st.info(
                f"⚠️ Client exists (Ref: {c_ref}, Serial: {c_serial}). "
                "Overwrite is ON – changes will update existing invoice."
            )
        else:
            st.warning(
                f"⚠️ Client exists (Ref: {c_ref}, Serial: {c_serial}). "
                "Tick 'Overwrite' to update the existing invoice."
            )

    col3, col4 = st.columns(2)

    with col3:
        billing_qty = st.number_input(
            "Paid Units:",
            min_value=1,
            value=default_qty,
            key=f"qty_{mode}_{selected_label}"
        )
        notes = st.text_area(
            "Notes:",
            value=default_notes,
            key=f"note_{mode}"
        )

    with col4:
        gen_by_input = st.text_input(
            "Generated By:",
            value="",
            placeholder="Leave blank for Default",
            key=f"gen_{mode}"
        )
        gen_by_to_save = (
            gen_by_input if gen_by_input.strip() else "Vesak Patient Care"
        )

    st.subheader("Services")
    inc_list, exc_list = get_base_lists(c_plan, row.get('Sub Service', 'All'))

    sc1, sc2 = st.columns(2)

    with sc1:
        st.text_area("Included", ", ".join(inc_list), disabled=True)

    with sc2:
        exc_final = st.multiselect(
            "Excluded (Click X to remove):",
            options=exc_list,
            default=exc_list,
            key=f"exc_{mode}_{c_ref}"
        )
        exc_text_for_pdf = ", ".join(exc_final)

    # --- UPDATED: Removed Nurse/Patient Buttons from here ---
    btn_save = False

    # ==========================================
    # SECTION 5: ADD WARNING DIALOG IN render_invoice_ui()
    # ==========================================
    # Location: In render_invoice_ui() function, BEFORE PDF generation buttons [Around Line ~1500-1600]
    # Status: UX ENHANCEMENT
    # What to add: Insert this warning BEFORE the Download/Print buttons

    # Add this code block in the render_invoice_ui() function where PDF buttons are shown:
    """
    # === NEW CODE: Add warning before PDF buttons ===
    st.warning(
        "⚠️ **Important Notice:** "
        "When generating Download or Print PDFs, if the invoice footer appears on a 2nd page, "
        "the page break may not be perfectly aligned. "
        "**Recommended:** Use 'Print → Save as PDF' for the best single-page output with watermark embedded.",
        icon="📄"
    )
    # === END NEW CODE ===
    """

    # ==========================================
    # SECTION 6: UPDATE PDF GENERATION IN render_invoice_ui()
    # ==========================================
    # Location: In render_invoice_ui() where buttons generate PDFs [Around Line ~1600-1700]
    # Status: ENHANCEMENT
    # What to change: Update the download button logic

    # NEW CODE (replacement):
    """
    col_download, col_print = st.columns(2)

    with col_download:
        if st.button("📥 Download PDF", key=f"btn_dl_{mode}"):
            html = construct_offline_invoice_html(record, logo_b64, "INVOICE")
            pdf_bytes = convert_html_to_pdf(html)
            if pdf_bytes:
                filename = generate_filename(
                    "Invoice",
                    record.get("Invoice Number", ""),
                    record.get("Customer Name", "")
                )
                st.download_button(
                    label="📥 Download PDF",
                    data=pdf_bytes,
                    file_name=filename,
                    mime="application/pdf"
                )
            else:
                st.error("❌ Error generating PDF. Please try again.")

    with col_print:
        if st.button("🖨️ Print & Save", key=f"btn_pr_{mode}"):
            html = construct_offline_invoice_html(record, logo_b64, "INVOICE")
            print_script = create_print_listener_script(
                generate_filename(
                    "Invoice",
                    record.get("Invoice Number", ""),
                    record.get("Customer Name", "")
                )
            )
            html_with_print = html.replace("</body>", f"{print_script}</body>")
            st.info(
                "ℹ️ PDF preview will open in a new window. "
                "Use Ctrl+P or Cmd+P to Print/Save as PDF."
            )
            components.html(html_with_print, height=1200, scrolling=True)
    """

    # ⭐ CHANGE #5 CONTINUED: BUTTON STATE LOGIC
    if conflict_exists:
        if chk_overwrite:
            if st.button("Overwrite Invoice", type="primary", key=f"b_ov_{mode}"): btn_save = True
        else:
            st.button("Create Invoice", disabled=True, key=f"b_cr_dis_{mode}")
    else:
        if st.button("Create Invoice", type="primary", key=f"b_cr_{mode}"): btn_save = True

    if btn_save:
        rate = float(row.get('Unit Rate', 0))
        total = rate * billing_qty
        
        # Point 9 & 10: Date Format DD-MM-YYYY (No Time)
        service_start_date = format_date_simple(inv_date_val)
        generated_at = datetime.datetime.now().strftime("%d-%m-%Y %H:%M:%S")

        # --- LOGIC FOR DETAILS COLUMN (RULES 1-6) ---
        p_raw_check = str(row.get('Period', '')).strip()
        p_check_lower = p_raw_check.lower()
        shift_raw_check = str(row.get('Shift', '')).strip()
        shift_check_lower = shift_raw_check.lower()
        
        details_text = ""
        
        # Rules 5 & 6 (Per Visit)
        if "per visit" in shift_check_lower:
            if billing_qty == 1: details_text = f"Paid for {billing_qty} Visit"
            else: details_text = f"Paid for {billing_qty} Visits"
        
        # Rules 1, 2, 3, 4 (Daily/Weekly/Monthly)
        elif "daily" in p_check_lower:
            if billing_qty == 1:
                details_text = f"Paid for {billing_qty} Day"
            elif billing_qty % 7 == 0:
                weeks_val = int(billing_qty / 7)
                if weeks_val == 1: details_text = f"Paid for {weeks_val} Week"
                else: details_text = f"Paid for {weeks_val} Weeks"
            else:
                details_text = f"Paid for {billing_qty} Days"
                
        elif "monthly" in p_check_lower:
            if billing_qty == 1: details_text = f"Paid for {billing_qty} Month"
            else: details_text = f"Paid for {billing_qty} Months"
            
        elif "weekly" in p_check_lower:
            if billing_qty == 1: details_text = f"Paid for {billing_qty} Week"
            else: details_text = f"Paid for {billing_qty} Weeks"
            
        else:
            details_text = f"Paid for {billing_qty} {p_raw_check}"
            
        if mode == "force_new": details_text += " (New)"
        # ---------------------------------------------

        # --- LOGIC FOR HISTORY PLAN NAME SAVING ---
        plan_to_save = c_plan
        sub_service_val = str(row.get('Sub Service', '')).strip()
        
        if c_plan == "Plan F: Rehabilitative Care":
            plan_to_save = f"Plan F: Rehabilitative Care and {sub_service_val}"
        elif c_plan == "A-la-carte Services":
            plan_to_save = f"Other Services - {sub_service_val}"
        # -------------------------------------------

        record = {
            "UID": "", 
            "Serial No.": c_serial, 
            "Ref. No.": c_ref,        
            "Invoice Number": inv_input, 
            "Date": format_date_with_suffix(inv_date_val),
            "Generated At": generated_at, 
            "Customer Name": c_name,
            "Age": c_age,
            "Gender": c_gender,
            "Location": c_loc,
            "Address": c_addr,
            "Mobile": c_mob, 
            "Plan": plan_to_save,
            "Shift": c_shift,
            "Recurring Service": c_rec,
            "Period": c_period,
            "Visits": c_visits,
            "Amount": rate, 
            "Amount Paid": total, 
            "Notes / Remarks": notes, 
            "Generated By": gen_by_to_save, 
            "Service Started": service_start_date,
            "Service Ended": "",
            "Details": details_text,
            "Paid for Raw": billing_qty,
            "Referral Code": c_ref_code,
            "Referral Name": c_ref_name,
            "Referral Credit": c_ref_credit
        }
        
        # ⭐ CHANGE #6: UPDATE vs APPEND LOGIC
        if conflict_exists and chk_overwrite and existing_row_idx:
            record["UID"] = df_history.iloc[existing_row_idx-2]["UID"] 
            try:
                actual_uid = sheet_obj.cell(existing_row_idx, 1).value
                record["UID"] = actual_uid
            except: pass
            
            update_invoice_in_gsheet(record, sheet_obj, existing_row_idx)
            st.success(f"Overwritten Row {existing_row_idx}!")
        else:
            save_invoice_to_gsheet(record, sheet_obj)
            st.success("Created New Row!")
        st.balloons()

        # === NEW: RESET / SET STATE AFTER SAVE ===
        if conflict_exists and chk_overwrite and existing_row_idx:
            # After overwrite, keep overwrite ON for same client
            st.session_state.chk_overwrite = True
        else:
            # After creating a NEW invoice, also set overwrite ON
            st.session_state.chk_overwrite = True

        # Always reset invoice date widget to today
        st.session_state[f"inv_d_{mode}"] = datetime.date.today()
        # ==========================================

        # === AUTO SET OVERWRITE ===
        # Mark this invoice as new so we force overwrite on next view
        st.session_state[f"ow_{mode}"] = True
        st.warning("⚠️ Client Exists. 'Overwrite' to update this client.")

        # === RESET STATE AFTER SAVE ===
        # Reset invoice date to today and overwrite checkbox
        st.session_state[f"inv_d_{mode}"] = datetime.date.today()
        st.session_state[f"ow_{mode}"] = False
        st.success("🔥 State reset ready for next invoice.")

    if btn_save:
        doc_type = "Invoice"
        
        rate = float(row.get('Unit Rate', 0))
        total = rate * billing_qty
        pdf_date_str = format_date_with_suffix(inv_date_val)
        
        file_name = generate_filename(doc_type, inv_input, c_name)

        
        # --- PREPARE DATA FOR HTML INJECTION ---
        desc_col_html = construct_description_html(row)
        amount_col_html = construct_amount_html(row, billing_qty)
        inc_def = inc_list
        final_exc = exc_final
        
        # --- LOGIC FOR PDF DESCRIPTION TEXT ---
        pdf_display_plan = c_plan
        sub_srv_txt = str(row.get('Sub Service', '')).strip()
        if c_plan == "Plan A: Patient Attendant Care":
            pdf_display_plan = "Patient Care Service"
        elif c_plan == "Plan B: Skilled Nursing":
            pdf_display_plan = "Nurse Service"
        elif c_plan == "Plan C: Chronic Management":
            pdf_display_plan = "Chronic and Holistic Healthcare Service"
        elif c_plan == "Plan D: Elderly Companion":
            pdf_display_plan = "Elderly and Well-being Care"
        elif c_plan == "Plan E: Maternal & Newborn":
            pdf_display_plan = "Maternal & Newborn - Support for Women during and after Pregnancy"
        elif c_plan == "Plan F: Rehabilitative Care":
            pdf_display_plan = f"Rehabilitative Care for {sub_srv_txt}"
        elif c_plan == "A-la-carte Services":
            pdf_display_plan = f"Other Service - {sub_srv_txt}"
        
        clean_plan = pdf_display_plan
        # --------------------------------------
        
        final_notes = notes
        
        ig_b64 = "" 
        fb_b64 = ""
        
        fmt_date = pdf_date_str
        inv_num = inv_input
        
        inc_html = "".join([f'<li class="mb-1 text-xs text-gray-700">{item}</li>' for item in inc_def])
        exc_html = "".join([f'<li class="mb-1 text-[10px] text-gray-500">{item}</li>' for item in final_exc])

        notes_section = ""
        if final_notes:
            notes_section = f"""<div class="mt-6 p-4 bg-gray-50 border border-gray-100 rounded"><h4 class="font-bold text-vesak-navy text-xs mb-1">NOTES:</h4><p class="text-xs text-gray-600 whitespace-pre-wrap">{final_notes}</p></div>"""

        # --- WEB PREVIEW TEMPLATE (Tailwind CSS) ---
        html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script>
        tailwind.config = {{
            theme: {{
                extend: {{
                    colors: {{ vesak: {{ navy: '#002147', gold: '#C5A065', orange: '#CC4E00' }} }},
                    fontFamily: {{ serif: ['"Playfair Display"', 'serif'], sans: ['"Lato"', 'sans-serif'] }}
                }}
            }}
        }}
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;600;700&display=swap');
    
        body {{
            font-family: 'Lato', sans-serif;
            background: #f0f0f0;
            margin: 0;
        }}
    
        .invoice-page {{
            position: relative;
            background: white;
            width: 210mm;
            height: 297mm;
            padding: 30px;
            padding-bottom: 120px; /* 🔒 Space for thank-you + footer */
            overflow: hidden;
            box-shadow: 0 10px 25px -5px rgba(0,0,0,0.05);
            display: flex;
            flex-direction: column;
    
            margin-left: auto;
            margin-right: auto;
        }}
    
        main {{
            flex: none;
        }}
    
        /* ✅ Thank-you text: centered & anchored near footer */
        main > .text-center {{
            margin-top: 40px;
            margin-bottom: 10px;
            text-align: center;
        }}
    
        /* ✅ Footer: TRUE horizontal centering */
        footer {{
            position: absolute;
            bottom: 7mm; /* ⬇️ slightly lower */
            left: 30px;
            right: 30px;
            text-align: center;
        }}
    
        .watermark-container {{
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translateX(-50%) translateY(-50%);
            pointer-events: none;
            z-index: 0;
        }}
    
        .watermark-text {{
            font-family: 'Playfair Display', serif;
            font-size: 80px;
            font-weight: 800;
            color: rgba(0, 33, 71, 0.04);
            letter-spacing: 0.25em;
        }}
    
        @media print {{
            body {{
                background: white;
                -webkit-print-color-adjust: exact;
            }}

            .watermark-container {{
                opacity: 0.04 !important;
            }}

            .watermark-text,
            .watermark-container img {{
            opacity: 0.04 !important;  /* keep subtle but force render */
            }}
    
            .invoice-page {{
                width: 210mm;
                height: 297mm;
                padding: 20px;
                padding-bottom: 90px;
                box-shadow: none;
            }}
    
            footer {{
                bottom: 7mm;
                width: calc(100% - 40px);
            }}
    
            .no-print {{
                display: none !important;
            }}    
            
        }}
    </style>
</head>
<body class="py-10">
    <div class="max-w-[210mm] mx-auto mb-6 flex justify-end gap-3 no-print px-4">
        <button onclick="window.print()" class="bg-gray-600 text-white px-5 py-2 rounded shadow hover:bg-gray-800 transition font-bold text-xs uppercase tracking-widest">
            <i class="fas fa-print mr-2"></i> Print / Save Vector PDF
        </button>
        <button onclick="generatePDF()" class="bg-vesak-navy text-white px-6 py-2 rounded shadow hover:bg-vesak-gold transition font-bold text-xs uppercase tracking-widest">
            <i class="fas fa-download mr-2"></i> Download PDF
        </button>
    </div>

    <div class="invoice-page" id="invoice-content">
        <div class="watermark-container">
            <img src="data:image/png;base64,{logo_b64}" style="display:block; margin:0; padding:0; width:300px; opacity:0.04;">
            <div class="watermark-text mt-4">VESAK</div>
        </div>

        <header class="relative z-10 w-full mb-10">
            <div class="flex justify-between items-start border-b border-gray-100 pb-6">
                <div class="flex items-center gap-5">
                    <img src="data:image/png;base64,{logo_b64}" class="w-20 h-auto">
                    <div>
                        <h1 class="font-serif text-2xl font-bold text-vesak-navy tracking-wide leading-none mb-2">
                            Vesak Care <span class="text-vesak-gold font-normal">Foundation</span>
                        </h1>
                        <div class="flex flex-col text-xs text-gray-500 font-light tracking-wide space-y-0.5">
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Web</span> vesakcare.com</span>
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Email</span> vesakcare@gmail.com</span>
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Phone</span> +91 7777 000 878</span>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <span class="block font-serif text-3xl text-gray-200 tracking-widest mb-2">INVOICE</span>
                    <div class="text-xs text-vesak-navy">
                        <div class="mb-1"><span class="text-gray-400 uppercase tracking-wider text-[10px] mr-2">Date</span> <b>{fmt_date}</b></div>
                        <div><span class="text-gray-400 uppercase tracking-wider text-[10px] mr-2">No.</span> <b>{inv_num}</b></div>
                    </div>
                </div>
            </div>
        </header>

        <main class="flex-grow relative z-10">
            
            <div class="flex mb-10 bg-gray-50 border-l-4 border-vesak-navy">
                <div class="w-1/2 p-4 border-r border-gray-200">
                    <div class="text-[10px] font-bold text-vesak-gold uppercase mb-1">Billed To</div>
                    <div class="text-lg font-bold text-vesak-navy">{c_name}</div>
                    <div class="flex gap-4 mt-2 text-xs text-gray-600">
                        <div class="flex items-center gap-1"><i class="fas fa-user text-vesak-gold"></i> {c_gender}</div>
                        <div class="flex items-center gap-1"><i class="fas fa-birthday-cake text-vesak-gold"></i> {c_age} Yrs</div>
                    </div>
                </div>
                <div class="w-1/2 p-4 flex flex-col justify-center">
                    <div class="flex items-center gap-2 text-xs text-gray-600 mb-2">
                        <i class="fas fa-phone-alt text-vesak-gold w-4"></i> {c_mob}
                    </div>
                    <div class="flex items-start gap-2 text-xs text-gray-600">
                        <i class="fas fa-map-marker-alt text-vesak-gold w-4 mt-0.5"></i> 
                        <span class="leading-tight">{c_addr}</span>
                    </div>
                </div>
            </div>

            <table class="w-full mb-8">
                <thead>
                    <tr class="bg-vesak-navy text-white text-xs uppercase tracking-wider text-left">
                        <th class="p-3 w-3/5">Description</th>
                        <th class="p-3 w-2/5 text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="border-b border-gray-100">
                        <td class="p-4 align-top">
                            <div class="font-bold text-sm text-gray-800">{clean_plan}</div>
                            {desc_col_html}
                        </td>
                        <td class="p-4 text-right font-bold text-sm text-gray-800 align-top">
                            {amount_col_html}
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="grid grid-cols-2 gap-8">
                <div>
                    <h4 class="text-xs font-bold text-vesak-navy uppercase border-b border-vesak-gold pb-1 mb-3">Services Included</h4>
                    <ul class="list-disc pl-4 space-y-1">{inc_html}</ul>
                </div>
                <div>
                    <h4 class="text-xs font-bold text-gray-400 uppercase border-b border-gray-200 pb-1 mb-3">Services Not Included</h4>
                    <ul class="columns-1 text-[10px] text-gray-400 space-y-1">{exc_html}</ul>
                </div>
            </div>

            {notes_section}
            
        </main>

        <footer class="z-10">
            
            <div class="text-center text-xs text-gray-400 italic mb-4">
                Thank you for choosing Vesak Care Foundation!
            </div>
            
            <div class="w-full h-px bg-gradient-to-r from-gray-100 via-vesak-gold to-gray-100 opacity-50 mb-4"></div>
            
            <div class="flex justify-between items-center text-xs text-gray-500 h-10">
                <div>
                    <p class="font-serif italic text-vesak-navy mb-1 text-sm">Our Offices</p>
                    <div class="flex gap-2">
                        <span>Pune</span><span class="text-vesak-gold">•</span>
                        <span>Mumbai</span><span class="text-vesak-gold">•</span>
                        <span>Kolhapur</span>
                    </div>
                </div>

                <div class="flex items-center gap-6">
                    <a href="https://www.instagram.com/VesakCare/" target="_blank" class="flex items-center gap-2 text-gray-500 hover:text-vesak-gold transition-colors">
                        <i class="fab fa-instagram text-lg"></i>
                        <span>@VesakCare</span>
                    </a>
                    
                    <a href="https://www.facebook.com/VesakCare/" target="_blank" class="flex items-center gap-2 text-gray-500 hover:text-vesak-gold transition-colors">
                        <i class="fab fa-facebook text-lg"></i>
                        <span>@VesakCare</span>
                    </a>
                </div>
            </div>
        
            <div class="mt-4 w-full h-1 bg-vesak-navy"></div>                
                
        </footer>
    </div>

    <script>
        function generatePDF() {{
            const element = document.getElementById('invoice-content');
            const opt = {{
                margin: [0.5, 0.5, 0.5, 0.5],
                filename: '{file_name}',
                image: {{ type: 'jpeg', quality: 1 }},
                html2canvas: {{ scale: 2, useCORS: true, letterRendering: true, scrollY: 0 }},
                jsPDF: {{ unit: 'mm', format: 'a4', orientation: 'portrait' }}
            }};
            html2pdf().set(opt).from(element).save();
        }}
    </script>
</body>
</html>
"""
        # RENDER THE HTML COMPONENT SO THE USER CAN SEE AND CLICK DOWNLOAD
        components.html(html_content, height=1000, scrolling=True)

if raw_file_obj:
    try:
        filename = getattr(raw_file_obj, "name", "data.xlsx")
        is_excel = filename.endswith('.xlsx')
        
        if is_excel:
            try:
                df = pd.read_excel(raw_file_obj, sheet_name='Confirmed', engine='openpyxl')
                st.sidebar.success("✅ Reading 'Confirmed' Sheet from Vesak Care - Patient Logs")
            except ValueError:
                st.error("❌ CRITICAL ERROR: The sheet 'Confirmed' was not found in the uploaded workbook.")
                st.stop()
        else:
            df = pd.read_csv(raw_file_obj)
        
        df = normalize_columns(df, COLUMN_ALIASES)
        
        with tab1: render_invoice_ui(df, mode="standard")
        with tab2: render_invoice_ui(df, mode="force_new")
        
        with tab3:
            st.header("©️ Duplicate Invoice")
            client = get_gspread_client()
            mid = extract_id_from_url(sys_config.get("master_sheet_url"))
            dup_date = st.date_input("Select Month:", value=datetime.date.today())
            mmm_yy = dup_date.strftime("%b-%y")
            
            if client and mid:
                try:
                    wb = client.open_by_key(mid)
                    ws = wb.worksheet(mmm_yy)
                    df_hist = pd.DataFrame(ws.get_all_records())
                    if not df_hist.empty and 'Invoice Number' in df_hist.columns:
                        df_hist['Display'] = df_hist['Invoice Number'].astype(str) + " - " + df_hist['Customer Name']
                        sel_dup = st.selectbox("Select Invoice:", df_hist['Display'].unique())
                        if sel_dup:
                            row = df_hist[df_hist['Display'] == sel_dup].iloc[0]
                            st.info(f"Selected: {row['Customer Name']}")
                            if st.button("Generate Duplicate PDF"):
                                data_map = row.to_dict()
                                data_map['Paid for Raw'] = row.get('Paid for', 1) 
                                html_dup = construct_offline_invoice_html(data_map, logo_b64, doc_type="DUPLICATE INVOICE")
                                pdf_dup = convert_html_to_pdf(html_dup)
                                
                                if pdf_dup:
                                    st.download_button("Download PDF", pdf_dup, file_name=f"Duplicate-{row['Invoice Number']}.pdf")
                                else:
                                    st.error("Error generating PDF file.")
                    else: st.warning("No records found in this month.")
                except Exception as e: st.error(f"Could not load history for this month: {e}")

        with tab4:
            st.header("🛠 Manage Services")
            SERVICES_MASTER = {
                "Plan A: Patient Attendant Care": ["All", "Basic Care", "Assistance with Activities for Daily Living", "Feeding & Oral Hygiene", "Mobility Support & Transfers", "Bed Bath and Emptying Bedpans", "Catheter & Ostomy Care"],
                "Plan B: Skilled Nursing": ["All", "Intravenous (IV) Therapy & Injections", "Medication Management", "Advanced Wound Care", "Catheter & Ostomy Care", "Post-Surgical Care"],
                "Plan C: Chronic Management": ["All", "Care for Bed-Ridden Patients", "Dementia & Alzheimer's Care", "Disability Support"],
                "Plan D: Elderly Companion": ["All", "Companionship & Conversation", "Fall Prevention & Mobility", "Light Meal Preparation"],
                "Plan E: Maternal & Newborn": ["All", "Postnatal & Maternal Care", "Newborn Care Assistance"],
                "Plan F: Rehabilitative Care": ["Therapeutic Massage", "Exercise Therapy", "Geriatric Rehabilitation", "Neuro Rehabilitation", "Pain Management", "Post Op Rehab"],
                "A-la-carte Services": ["Hospital Visits", "Medical Equipment", "Medicines", "Diagnostic Services", "Nutrition Consultation", "Ambulance", "Doctor Visits", "X-Ray", "Blood Collection"]
            }
            ms_plan = st.selectbox("Select Plan to View:", list(SERVICES_MASTER.keys()))
            ms_sub = st.text_input("Simulate Sub-Services Input:", value="All")
            inc, exc = get_base_lists(ms_plan, ms_sub)
            c1, c2 = st.columns(2)
            with c1: 
                st.success(f"✅ Included ({len(inc)})")
                for i in inc: st.write(f"- {i}")
            with c2: 
                st.error(f"❌ Excluded ({len(exc)})")
                for e in exc: st.write(f"- {e}")
        
        with tab5:
            st.header("Nurse Management")
            client = get_gspread_client()
            mid = extract_id_from_url(sys_config.get("master_sheet_url"))
            
            if client and mid:
                try:
                    wb = client.open_by_key(mid)
                    ws = wb.worksheet(datetime.date.today().strftime("%b-%y"))
                    st.write("Enter Invoice Number to manage nurse payments:")
                    inv_to_pay = st.text_input("Invoice No:")
                    st.divider()
                    col_n1, col_n2 = st.columns(2)
                    with col_n1:
                        amt = st.number_input("Nurse Payment Amount:", min_value=0.0)
                        nm = st.text_input("Nurse Name:")
                    with col_n2:
                        nm_extra = st.text_input("Nurse Name (Extra):")
                        nm_note = st.text_area("Nurse Note")
                    if st.button("Update Nurse Details (Overwrite)"):
                        success, form = update_nurse_management(ws, inv_to_pay, amt, nm, nm_extra, nm_note)
                        if success: st.success("✅ Nurse details updated successfully in sheet!")
                        else: st.error("❌ Invoice not found in current month's sheet.")
                except Exception as e: st.error(f"Error accessing sheet: {e}")
            else:
                st.warning("Please configure Master Sheet URL in Sidebar.")

        with tab6:
            st.header("📝 Create Agreements")
            
            use_filt_ag = st.checkbox("🔍 Enable Search Filters (Date/Location)", key="use_filt_ag")
            df_ag = df.copy()
            
            if use_filt_ag:
                c1, c2 = st.columns(2)
                with c1: f_dt = st.date_input("Filter Date:", value=datetime.date.today(), key="ag_dt")
                with c2: 
                    u_locs = ["All"] + sorted(list(df['Location'].astype(str).unique()))
                    f_lc = st.selectbox("Filter Location:", u_locs, key="ag_lc")
                
                if 'Call Date' in df_ag.columns:
                    df_ag['TempDate'] = pd.to_datetime(df_ag['Call Date'], errors='coerce').dt.date
                    df_ag = df_ag[df_ag['TempDate'] == f_dt]
                if f_lc != "All": df_ag = df_ag[df_ag['Location'].astype(str) == f_lc]
            
            df_ag['Ref_Clean'] = df_ag['Ref. No.'].astype(str).str.strip()
            df_ag['Label'] = df_ag['Name'].astype(str) + " (" + df_ag['Mobile'].astype(str) + ")"
            
            if df_ag.empty: st.warning("No customers found.")
            else:
                sel_cust_ag = st.selectbox("Select Customer for Agreement:", [""] + list(df_ag['Label'].unique()), key="sel_ag")
                if sel_cust_ag:
                    row_ag = df_ag[df_ag['Label'] == sel_cust_ag].iloc[0]
                    st.info(f"Selected: {row_ag['Name']} | Ref: {normalize_id(row_ag.get('Ref. No.'))}")
                    
                    c_ref_ag = normalize_id(row_ag.get('Ref. No.', ''))
                    pdf_date_str = format_date_with_suffix(datetime.date.today())
                    
                    col_b1, col_b2 = st.columns(2)
                    with col_b1: 
                        if st.button("Nurse Agreement", key="btn_nu_ag"):
                            display_type = "NURSE AGREEMENT"
                            file_name = generate_filename("Nurse", "AGR", row_ag['Name'])
                            html_content = f"""<!DOCTYPE html><html><head><style>@page {{ size: a4 portrait; margin: 1cm; }} body {{ font-family: 'Helvetica', sans-serif; }} .header {{ text-align: center; }}</style></head><body><div class="header"><img src="data:image/png;base64,{logo_b64}" width="100"><h2>Vesak Care Foundation</h2></div><h3>{display_type}</h3><p><strong>Ref:</strong> {c_ref_ag}</p><p><strong>Date:</strong> {pdf_date_str}</p><br><br><br><p>Authorized Signatory</p></body></html>"""
                            pdf_bytes = convert_html_to_pdf(html_content)
                            if pdf_bytes: st.download_button(f"⬇️ Download Nurse Agreement", data=pdf_bytes, file_name=file_name, mime="application/pdf")
                    
                    with col_b2: 
                        if st.button("Patient Agreement", key="btn_pa_ag"):
                            display_type = "PATIENT AGREEMENT"
                            file_name = generate_filename("Patient", "AGR", row_ag['Name'])
                            html_content = f"""<!DOCTYPE html><html><head><style>@page {{ size: a4 portrait; margin: 1cm; }} body {{ font-family: 'Helvetica', sans-serif; }} .header {{ text-align: center; }}</style></head><body><div class="header"><img src="data:image/png;base64,{logo_b64}" width="100"><h2>Vesak Care Foundation</h2></div><h3>{display_type}</h3><p><strong>Ref:</strong> {c_ref_ag}</p><p><strong>Date:</strong> {pdf_date_str}</p><br><br><br><p>Authorized Signatory</p></body></html>"""
                            pdf_bytes = convert_html_to_pdf(html_content)
                            if pdf_bytes: st.download_button(f"⬇️ Download Patient Agreement", data=pdf_bytes, file_name=file_name, mime="application/pdf")

    except Exception as e: st.error(f"Error: {e}")

