import streamlit as st
import pandas as pd
import base64
import os
import datetime
import requests
import math 
import re 
from io import BytesIO
from PIL import Image, ImageFile
import streamlit.components.v1 as components
from xhtml2pdf import pisa 
import gspread
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseUpload
import numpy as np
import traceback

# --- CRITICAL FIX FOR BROKEN IMAGES ---
ImageFile.LOAD_TRUNCATED_IMAGES = True

# ==========================================
# 1. SETUP & ASSET GENERATION
# ==========================================
st.set_page_config(page_title="Vesak Care Invoice", layout="wide", page_icon="🏥")

LOGO_FILE = "logo.png"
URL_CONFIG_FILE = "url_config.txt"

# --- HARDCODED FOLDER IDS ---
HISTORY_FOLDER_ID = "1e5iNxAwO8ly3_iAs2ONCyZO1CgQeFQhr"
AGREEMENTS_ROOT_ID = "16QWhwkhWS4S5nRWkPuusJ9UjQzf-2TKl"

# --- NEW: INVOICE ROOT FOLDER ID ---
# If left empty, the code will search/create "Vesak Invoices" in your Drive Root.
INVOICES_ROOT_ID = "" 

# --- CRITICAL: HARDCODED SHEET ID FOR 2025 ---
# Kept as fallback for 2025 specific logic
MANUAL_SHEET_ID_25 = "1aBhZrgqtdD-bLE28Ujaq6lODou211wMnIIL8wxuPK5Q"

# --- HEADERS (31 COLUMNS) ---
SHEET_HEADERS = [
    "UID", "Serial No.", "Ref. No.", "Invoice Number", "Date", "Generated At",
    "Customer Name", "Age", "Gender", "Location", "Address", "Mobile",
    "Plan", "Shift", "Recurring Service", "Period", "Visits", "Amount",
    "Notes / Remarks", "Generated By", "Amount Paid", "Details",
    "Service Started", "Service Ended", "Referral Code", "Referral Name",
    "Referral Credit", "Net Amount", "Nurse Payment", "Paid for", "Earnings"
]

# --- SESSION STATE INITIALIZATION ---
if 'chk_print_dup' not in st.session_state: st.session_state.chk_print_dup = False
if 'chk_overwrite' not in st.session_state: st.session_state.chk_overwrite = False
if 'active_tab_simulation' not in st.session_state: st.session_state.active_tab_simulation = "Generate"

# --- CREDENTIALS HANDLING ---
@st.cache_resource
def get_credentials():
    scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ]
    if "connections" in st.secrets and "gsheets" in st.secrets["connections"]:
        s_info = st.secrets["connections"]["gsheets"]
        private_key = s_info.get("private_key")
        if private_key: private_key = private_key.replace("\\n", "\n")
        creds_dict = {
            "type": s_info.get("type"),
            "project_id": s_info.get("project_id"),
            "private_key_id": s_info.get("private_key_id"),
            "private_key": private_key,
            "client_email": s_info.get("client_email"),
            "client_id": s_info.get("client_id"),
            "auth_uri": s_info.get("auth_uri"),
            "token_uri": s_info.get("token_uri"),
            "auth_provider_x509_cert_url": s_info.get("auth_provider_x509_cert_url"),
            "client_x509_cert_url": s_info.get("client_x509_cert_url"),
        }
        return Credentials.from_service_account_info(creds_dict, scopes=scopes)
    return None

def get_bot_email():
    try: return st.secrets["connections"]["gsheets"]["client_email"]
    except: return "Unknown"

# --- CONNECT TO GOOGLE DRIVE ---
@st.cache_resource
def get_drive_service():
    try:
        creds = get_credentials()
        if creds: return build('drive', 'v3', credentials=creds)
    except Exception as e: st.error(f"Drive Connection Error: {e}")
    return None

# ==========================================
# CRITICAL UPDATE: FOLDER & FILE LOGIC
# ==========================================

@st.cache_data(show_spinner=False)
def robust_file_downloader(url):
    """
    Downloads file using a session to persist cookies through redirects.
    This fixes 403 errors on public OneDrive links.
    """
    session = requests.Session()
    session.headers.update({
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Referer': 'https://www.google.com/'
    })

    download_url = url
    
    # 1. Clean the URL (Remove existing parameters)
    if "?" in url:
        base_url = url.split("?")[0]
    else:
        base_url = url

    # 2. Append download command
    if "1drv.ms" in url or "sharepoint" in url or "onedrive" in url:
        download_url = base_url + "?download=1"
    
    try:
        # Attempt download
        response = session.get(download_url, verify=False, allow_redirects=True)
        
        # Check if successful
        if response.status_code == 200:
            content_type = response.headers.get('Content-Type', '').lower()
            if 'text/html' in content_type and len(response.content) < 5000:
                response = session.get(url, verify=False, allow_redirects=True)
            
            return BytesIO(response.content)
            
        raise Exception(f"Status Code: {response.status_code}")
        
    except Exception as e:
        raise Exception(f"Download failed: {e}. Ensure the OneDrive link is set to 'Anyone with the link'.")

def get_or_create_folder(service, folder_name, parent_id=None):
    safe_name = folder_name.replace("'", "\\'")
    query = f"mimeType='application/vnd.google-apps.folder' and name='{safe_name}' and trashed=false"
    if parent_id:
        query += f" and '{parent_id}' in parents"
    
    try:
        # 1. Check if exists
        results = service.files().list(q=query, fields="files(id, name)").execute()
        files = results.get('files', [])
        if files:
            return files[0]['id'] 
        
        # 2. If not, create it
        file_metadata = {
            'name': folder_name, 
            'mimeType': 'application/vnd.google-apps.folder'
        }
        if parent_id:
            file_metadata['parents'] = [parent_id]
            
        file = service.files().create(body=file_metadata, fields='id').execute()
        return file.get('id')
        
    except Exception as e:
        try:
            results = service.files().list(q=query, fields="files(id, name)").execute()
            files = results.get('files', [])
            if files: return files[0]['id']
        except:
            pass
        st.error(f"CRITICAL ERROR: Could not create folder '{folder_name}'.")
        st.warning(f"⚠️ PLEASE MANUALLY CREATE THE FOLDER: '{folder_name}' in Google Drive immediately.")
        raise e

def get_target_folder_hierarchy(service, doc_type, date_obj):
    yy = date_obj.strftime("%y") 
    mmm_yy = date_obj.strftime("%b-%y") # e.g., Jan-26
    
    if mmm_yy.startswith("Jan") and mmm_yy[3] != '-': 
        mmm_yy = date_obj.strftime("%b-%y")

    # DEFINE PATHS BASED ON DOC TYPE
    root_id = None
    level2_name = ""
    
    if doc_type == "Invoice":
        if INVOICES_ROOT_ID:
            root_id = INVOICES_ROOT_ID
        else:
            try:
                root_id = get_or_create_folder(service, "Vesak Invoices")
            except:
                st.warning("⚠️ Could not find 'Vesak Invoices' folder. Please create it manually.")
                return None
        level2_name = f"Invoice-{yy}"

    elif doc_type == "Nurse":
        root_id = AGREEMENTS_ROOT_ID
        level2_name = f"Nurse Agreement {yy}"

    elif doc_type == "Patient":
        root_id = AGREEMENTS_ROOT_ID
        level2_name = f"Patient Agreement {yy}"

    # --- EXECUTE 5-STEP ROBUST LOGIC ---
    if root_id:
        try:
            # Level 2 (Yearly)
            year_id = get_or_create_folder(service, level2_name, parent_id=root_id)
            
            # Level 3 (Monthly)
            month_id = get_or_create_folder(service, mmm_yy, parent_id=year_id)
            
            return month_id
        except Exception as e:
            st.error(f"❌ Critical Storage/Permission Error: {e}")
            st.info(f"ℹ️ Action Required: Please go to Google Drive > '{doc_type}' Folders and manually create folder: '{level2_name}' and inside it '{mmm_yy}'.")
            return None
            
    return None

def find_file_in_folder(service, folder_id, file_name):
    try:
        query = f"name = '{file_name}' and '{folder_id}' in parents and trashed = false"
        results = service.files().list(q=query, fields="files(id, name)").execute()
        files = results.get('files', [])
        if files: return files[0]['id']
        return None
    except: return None

def update_drive_file(service, file_id, file_content_bytes):
    try:
        media = MediaIoBaseUpload(BytesIO(file_content_bytes), mimetype='application/pdf')
        service.files().update(fileId=file_id, media_body=media).execute()
        return True
    except Exception as e:
        print(f"Update failed: {e}")
        return False

def upload_to_drive(service, folder_id, file_name, file_content_bytes):
    file_metadata = {'name': file_name, 'parents': [folder_id]}
    media = MediaIoBaseUpload(BytesIO(file_content_bytes), mimetype='application/pdf')
    try:
        file = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
        return file.get('id')
    except Exception as e:
        if "storage quota" in str(e).lower():
            try: service.files().emptyTrash().execute()
            except: pass
            file = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
            return file.get('id')
        return None

def generate_filename(doc_type, invoice_no, customer_name):
    prefix_map = { "Invoice": "IN", "Nurse": "NU", "Patient": "PA" }
    prefix = prefix_map.get(doc_type, "DOC")
    clean_name = re.sub(r'[^a-zA-Z0-9]', '-', str(customer_name)).upper()
    clean_name = re.sub(r'-+', '-', clean_name).strip('-') 
    return f"{prefix}-{invoice_no}-{clean_name}.pdf"

# ==========================================
# CRITICAL UPDATE: FORMATTING
# ==========================================

def format_worksheet_header(ws):
    try:
        ws.format("A1:AE1", {
            "backgroundColor": {"red": 0.576, "green": 0.768, "blue": 0.49},
            "textFormat": {
                "foregroundColor": {"red": 1.0, "green": 1.0, "blue": 1.0},
                "bold": True,
                "fontSize": 10
            },
            "horizontalAlignment": "CENTER",
            "verticalAlignment": "MIDDLE",
            "wrapStrategy": "WRAP"
        })
        ws.format("X2:X1000", {
             "backgroundColor": {"red": 0.917, "green": 0.6, "blue": 0.6},
             "textFormat": {"foregroundColor": {"red": 0.0, "green": 0.0, "blue": 0.0}, "bold": False}
        })
        ws.freeze(rows=1)
        widths = [ 50, 50, 100, 120, 100, 120, 180, 50, 60, 100, 200, 100, 120, 100, 80, 80, 60, 80, 150, 100, 100, 200, 100, 100, 100, 120, 80, 100, 100, 80, 100 ]
        for i, width in enumerate(widths):
            ws.set_column_width(i, width)
    except Exception as e:
        print(f"Formatting warning: {e}")

# --- SMART SHEET CONNECTION ---
def get_active_sheet_client(drive_service, date_obj):
    try:
        creds = get_credentials()
        if not creds: return None
        client = gspread.authorize(creds)
        yy = date_obj.strftime("%y")
        mmm_yy = date_obj.strftime("%b-%y").capitalize()
        wb_name = f"Vesak_Invoice_{yy}"
        spreadsheet = None

        if yy == "25" and MANUAL_SHEET_ID_25:
            try: spreadsheet = client.open_by_key(MANUAL_SHEET_ID_25)
            except: pass

        if spreadsheet is None:
            try: spreadsheet = client.open(wb_name)
            except gspread.exceptions.SpreadsheetNotFound:
                bot_email = get_bot_email()
                st.markdown(f"### 🛑 New Workbook Required: `{wb_name}`\nCreate `{wb_name}` and share with `{bot_email}`")
                if st.button("I have created it"): st.rerun()
                st.stop()

        worksheet = None
        try:
            worksheet = spreadsheet.worksheet(mmm_yy)
        except gspread.exceptions.WorksheetNotFound:
            try:
                default_sheet = spreadsheet.worksheet("Sheet1")
                if len(default_sheet.get_all_values()) < 2:
                    default_sheet.update_title(mmm_yy)
                    worksheet = default_sheet
                    if not worksheet.get_all_values(): worksheet.append_row(SHEET_HEADERS)
                    format_worksheet_header(worksheet)
                else:
                    worksheet = spreadsheet.add_worksheet(title=mmm_yy, rows="1000", cols="31")
                    worksheet.append_row(SHEET_HEADERS)
                    format_worksheet_header(worksheet)
            except gspread.exceptions.WorksheetNotFound:
                worksheet = spreadsheet.add_worksheet(title=mmm_yy, rows="1000", cols="31")
                worksheet.append_row(SHEET_HEADERS)
                format_worksheet_header(worksheet)
        return spreadsheet, worksheet
    except Exception as e:
        st.error(f"Google Sheet Error: {e}"); return None, None

# --- MASTER HISTORY LOGIC ---
@st.cache_data(ttl=60)
def get_master_history(current_wb_name, _current_sheet_obj):
    frames = []
    if MANUAL_SHEET_ID_25:
        try:
            creds = get_credentials()
            client = gspread.authorize(creds)
            wb_25 = client.open_by_key(MANUAL_SHEET_ID_25)
            for ws in wb_25.worksheets():
                 data = ws.get_all_records()
                 if data: frames.append(pd.DataFrame(data))
        except: pass
    if _current_sheet_obj:
        try:
            if _current_sheet_obj.spreadsheet.id != MANUAL_SHEET_ID_25:
                data_curr = _current_sheet_obj.get_all_records()
                if data_curr: frames.append(pd.DataFrame(data_curr))
        except: pass
    if not frames: return pd.DataFrame()
    master_df = pd.concat(frames, ignore_index=True)
    if 'Invoice Number' in master_df.columns:
        master_df['Invoice Number'] = master_df['Invoice Number'].astype(str)
    return master_df.dropna(how='all')

# --- HELPER FUNCTIONS ---
def get_absolute_path(filename):
    if os.path.exists(filename): return os.path.abspath(filename).replace('\\', '/')
    return None

def get_clean_image_base64(file_path):
    if not os.path.exists(file_path): return None
    try:
        img = Image.open(file_path).convert("RGBA")
        buffer = BytesIO()
        img.save(buffer, format="PNG", optimize=True)
        return base64.b64encode(buffer.getvalue()).decode('utf-8')
    except: return None

def clean_text(text): return str(text).strip() if isinstance(text, str) else str(text)

def format_date_with_suffix(d):
    if pd.isna(d) or str(d).lower() in ['nan', 'n/a']: return "N/A"
    try:
        if not isinstance(d, (datetime.date, datetime.datetime)): d = pd.to_datetime(d)
        if isinstance(d, datetime.datetime): d = d.date()
        day = d.day
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th") if not 10 < day < 14 else "th"
        return d.strftime(f"%b. {day}{suffix} %Y")
    except: return str(d)

def load_config_path(file_name):
    if os.path.exists(file_name):
        with open(file_name, "r") as f: return f.read().strip()
    return ""

def save_config_path(path, file_name):
    with open(file_name, "w") as f: f.write(path.replace('"', '').strip())
    return path

# --- DATABASE HELPERS ---
def get_next_invoice_number_gsheet(date_obj, df_hist, location_str):
    loc_clean = str(location_str).strip().lower()
    loc_code = "MUM" if "mumbai" in loc_clean else "KOP" if "kolhapur" in loc_clean else "PUN"
    date_part = date_obj.strftime('%y%m%d')
    prefix_str = f"{loc_code}-{date_part}-"
    next_seq = 1
    if not df_hist.empty and 'Invoice Number' in df_hist.columns:
        df_hist['Invoice Number'] = df_hist['Invoice Number'].astype(str)
        day_loc_inv = df_hist[df_hist['Invoice Number'].str.startswith(prefix_str)]
        if not day_loc_inv.empty:
            try:
                day_loc_inv['Seq'] = day_loc_inv['Invoice Number'].apply(lambda x: int(x.split('-')[-1]) if '-' in x else 0)
                next_seq = day_loc_inv['Seq'].max() + 1
            except: pass
    return f"{prefix_str}{next_seq:03d}"

def get_next_uid_gsheet(df_hist):
    if df_hist.empty or 'UID' not in df_hist.columns: return "0001"
    try:
        uids = pd.to_numeric(df_hist['UID'], errors='coerce').fillna(0)
        return f"{int(uids.max()) + 1:04d}"
    except: return "0001"

def get_active_invoice_record(df_hist, ref_no):
    if df_hist.empty or 'Ref. No.' not in df_hist.columns: return None
    df_hist['Ref_Clean'] = df_hist['Ref. No.'].astype(str).str.strip()
    target_ref = str(ref_no).strip()
    client_rows = df_hist[df_hist['Ref_Clean'] == target_ref]
    if client_rows.empty: return None
    if 'Service Ended' in client_rows.columns:
        client_rows['Service_Ended_Clean'] = client_rows['Service Ended'].fillna('').astype(str).str.strip()
        active_rows = client_rows[client_rows['Service_Ended_Clean'] == '']
        if not active_rows.empty: return active_rows.iloc[-1]
    return None

def check_if_service_ended_history(df_hist, ref_no):
    if df_hist.empty or 'Ref. No.' not in df_hist.columns: return False
    df_hist['Ref_Clean'] = df_hist['Ref. No.'].astype(str).str.strip()
    client_rows = df_hist[df_hist['Ref_Clean'] == str(ref_no).strip()]
    if client_rows.empty: return False 
    last_row = client_rows.iloc[-1]
    svc_end = ""
    if 'Service Ended' in last_row: svc_end = str(last_row['Service Ended']).strip()
    return svc_end != ""

def get_last_billing_qty(df_hist, customer_name, mobile):
    if df_hist.empty or 'Customer Name' not in df_hist.columns: return 1
    mask = (df_hist['Customer Name'].astype(str).str.lower() == str(customer_name).lower())
    client_history = df_hist[mask]
    if not client_history.empty:
        match = re.search(r'Paid for (\d+)', str(client_history.iloc[-1].get('Details', '')))
        if match: return int(match.group(1))
    return 1

# --- SAVE TO GSHEET ---
def save_invoice_to_gsheet(data_dict, sheet_obj):
    if sheet_obj is None: return False
    try:
        all_vals = sheet_obj.get_all_values()
        next_row_num = len(all_vals) + 1
        formula_net_amount = f"=U{next_row_num}-AA{next_row_num}"
        formula_earnings = f"=AB{next_row_num}-(AC{next_row_num}*AD{next_row_num})"
        
        details_txt = data_dict.get("Details", "")
        qty_extracted = 1
        match = re.search(r'Paid for (\d+)', details_txt)
        if match: qty_extracted = int(match.group(1))

        row_values = [
            data_dict.get("UID", ""), data_dict.get("Serial No.", ""), data_dict.get("Ref. No.", ""),
            data_dict.get("Invoice Number", ""), data_dict.get("Date", ""), data_dict.get("Generated At", ""),
            data_dict.get("Customer Name", ""), data_dict.get("Age", ""), data_dict.get("Gender", ""),
            data_dict.get("Location", ""), data_dict.get("Address", ""), data_dict.get("Mobile", ""),
            data_dict.get("Plan", ""), data_dict.get("Shift", ""), data_dict.get("Recurring Service", ""),
            data_dict.get("Period", ""), data_dict.get("Visits", ""), data_dict.get("Amount", ""),
            data_dict.get("Notes / Remarks", ""), data_dict.get("Generated By", ""), data_dict.get("Amount Paid", ""),
            data_dict.get("Details", ""), data_dict.get("Service Started", ""), data_dict.get("Service Ended", ""),
            data_dict.get("Referral Code", ""), data_dict.get("Referral Name", ""), data_dict.get("Referral Credit", ""),
            formula_net_amount, "", qty_extracted, formula_earnings
        ]
        sheet_obj.append_row(row_values, value_input_option='USER_ENTERED')
        return True
    except Exception as e: st.error(f"Save Error: {e}"); return False

def update_invoice_in_gsheet(data_dict, sheet_obj, original_inv_to_find):
    if sheet_obj is None: return False
    try:
        cell = sheet_obj.find(str(original_inv_to_find).strip(), in_column=4)
        if cell:
            row_idx = cell.row
            row_values = [
                data_dict.get("UID", ""), data_dict.get("Serial No.", ""), data_dict.get("Ref. No.", ""),
                data_dict.get("Invoice Number", ""), data_dict.get("Date", ""), data_dict.get("Generated At", ""),
                data_dict.get("Customer Name", ""), data_dict.get("Age", ""), data_dict.get("Gender", ""),
                data_dict.get("Location", ""), data_dict.get("Address", ""), data_dict.get("Mobile", ""),
                data_dict.get("Plan", ""), data_dict.get("Shift", ""), data_dict.get("Recurring Service", ""),
                data_dict.get("Period", ""), data_dict.get("Visits", ""), data_dict.get("Amount", ""),
                data_dict.get("Notes / Remarks", ""), data_dict.get("Generated By", ""), data_dict.get("Amount Paid", ""),
                data_dict.get("Details", ""), data_dict.get("Service Started", ""), data_dict.get("Service Ended", "")
            ]
            range_name = f"A{row_idx}:X{row_idx}"
            sheet_obj.update(range_name, [row_values], value_input_option='USER_ENTERED')
            return True
        return False
    except Exception as e: st.error(f"Update Error: {e}"); return False

def update_nurse_payment(sheet_obj, invoice_number, payment_amount):
    if sheet_obj is None: return False
    try:
        cell = sheet_obj.find(str(invoice_number).strip(), in_column=4) 
        if cell:
            row_idx = cell.row
            details_val = sheet_obj.cell(row_idx, 22).value
            qty = 1
            if details_val:
                match = re.search(r'Paid for\s*:?\s*(\d+)', str(details_val), re.IGNORECASE)
                if match: qty = int(match.group(1))
            range_notation = f"AC{row_idx}:AD{row_idx}"
            sheet_obj.update(range_notation, [[payment_amount, qty]], value_input_option='USER_ENTERED')
            return True
        return False
    except Exception as e: st.error(f"Payment Error: {e}"); return False

def mark_service_ended(sheet_obj, invoice_number, end_date):
    if sheet_obj is None: return False, "No Sheet"
    try:
        cell = sheet_obj.find(str(invoice_number).strip(), in_column=4)
        if cell:
            end_time = end_date.strftime("%Y-%m-%d") + " " + datetime.datetime.now().strftime("%H:%M:%S")
            range_name = f"X{cell.row}"
            sheet_obj.update(range_name, [[end_time]])
            return True, end_time
        return False, "Invoice not found"
    except Exception as e: return False, str(e)

# ==========================================
# SYSTEM HEALTH CHECK FUNCTION (IMPROVED)
# ==========================================
def run_system_health_check(drive_service, sheet_obj_25_id, agreements_id, invoices_id_config):
    st.markdown("---")
    st.markdown("### 🕵️‍♂️ System Health Scan")
    
    issues_found = False
    
    # 1. CHECK GOOGLE DRIVE CONNECTION
    if drive_service:
        st.success("✅ Google Drive API: Connected")
    else:
        st.error("❌ Google Drive API: NOT Connected. Check secrets/credentials.")
        issues_found = True

    # 2. CHECK AGREEMENTS FOLDER
    try:
        if drive_service:
            # Check Agreements Root
            drive_service.files().get(fileId=agreements_id).execute()
            st.success(f"✅ Drive Folder 'Vesak Agreements': Found (ID: ...{agreements_id[-5:]})")
    except Exception as e:
        st.error(f"❌ Drive Folder 'Vesak Agreements' NOT FOUND. Check ID: {agreements_id}")
        issues_found = True

    # 3. CHECK INVOICES FOLDER
    if not invoices_id_config:
        st.warning("⚠️ 'Vesak Invoices' ID is empty. System will Auto-Search/Create it in Root.")
    else:
        try:
            if drive_service:
                drive_service.files().get(fileId=invoices_id_config).execute()
                st.success(f"✅ Drive Folder 'Vesak Invoices': Found (ID: ...{invoices_id_config[-5:]})")
        except Exception as e:
            st.error(f"❌ Drive Folder 'Vesak Invoices' NOT FOUND. Check ID: {invoices_id_config}")
            issues_found = True

    # 4. SMART WORKBOOK & SHEET CHECK (Dynamic Year)
    try:
        creds = get_credentials()
        client = gspread.authorize(creds)
        
        # A. Check Hardcoded 2025 Sheet (Legacy/Transition)
        try:
            client.open_by_key(sheet_obj_25_id)
            st.success(f"✅ Legacy 2025 Workbook (ID Based): Connected")
        except:
             st.warning(f"⚠️ Legacy 2025 Workbook ID not found or permission denied.")

        # B. Check Current & Previous Year Dynamic Workbooks
        now = datetime.datetime.now()
        current_yy = int(now.strftime("%y"))
        years_to_check = [current_yy - 1, current_yy] # Check Previous and Current Year
        
        for y_int in years_to_check:
            y_str = str(y_int)
            wb_name = f"Vesak_Invoice_{y_str}"
            
            # Determine which month to check (if it's current year, check current month, else check Dec)
            if y_int == current_yy:
                 check_month = now.strftime("%b-%y").capitalize() # e.g. Jan-26
            else:
                 check_month = f"Dec-{y_str}" # Just checking if Dec exists for previous year as sample

            try:
                wb = client.open(wb_name)
                st.success(f"✅ Workbook '{wb_name}': Found")
                
                # Check for specific month sheet
                try:
                    wb.worksheet(check_month)
                    st.success(f"   └── ✅ Sheet '{check_month}': Found inside")
                except:
                    st.warning(f"   └── ⚠️ Sheet '{check_month}' MISSING in '{wb_name}'. It will be auto-created when you generate an invoice.")
            except gspread.exceptions.SpreadsheetNotFound:
                if y_int == current_yy:
                     st.error(f"❌ Current Workbook '{wb_name}' NOT FOUND.")
                     st.info(f"   👉 Action: Create a Google Sheet named '{wb_name}' and share it with the bot email.")
                     issues_found = True
                else:
                     st.warning(f"⚠️ Previous Workbook '{wb_name}' not found (Might not be created yet).")

    except Exception as e:
        st.error(f"❌ Google Sheet Logic Failed: {e}")
        issues_found = True

    # 5. CHECK EXCEL/DATA SOURCE
    if 'raw_file_obj' in globals() and raw_file_obj:
         st.success("✅ Source Data: Excel/CSV File Loaded")
    elif os.path.exists(URL_CONFIG_FILE):
         with open(URL_CONFIG_FILE, "r") as f:
             url = f.read().strip()
             if url: st.success("✅ Source Data: OneDrive Link Configured")
             else: st.warning("⚠️ Source Data: No Link or File provided yet.")
    else:
         st.warning("⚠️ Source Data: Waiting for input...")

    if not issues_found:
        st.success("🌟 ALL SYSTEMS NORMAL.")
    else:
        st.error("🛑 CRITICAL ISSUES FOUND. PLEASE FIX ABOVE ERRORS.")

# ==========================================
# DATA LISTS & CONSTANTS
# ==========================================
SERVICES_MASTER = {
    "Plan A: Patient Attendant Care": ["All", "Basic Care", "Assistance with Activities for Daily Living", "Feeding & Oral Hygiene", "Mobility Support & Transfers", "Bed Bath and Emptying Bedpans", "Catheter & Ostomy Care"],
    "Plan B: Skilled Nursing": ["All", "Intravenous (IV) Therapy & Injections", "Medication Management", "Advanced Wound Care", "Catheter & Ostomy Care", "Post-Surgical Care"],
    "Plan C: Chronic Management": ["All", "Care for Bed-Ridden Patients", "Dementia & Alzheimer's Care", "Disability Support"],
    "Plan D: Elderly Companion": ["All", "Companionship & Conversation", "Fall Prevention & Mobility", "Light Meal Preparation"],
    "Plan E: Maternal & Newborn": ["All", "Postnatal & Maternal Care", "Newborn Care Assistance"],
    "Plan F: Rehabilitative Care": ["Therapeutic Massage", "Exercise Therapy", "Geriatric Rehabilitation", "Neuro Rehabilitation", "Pain Management", "Post Op Rehab"],
    "A-la-carte Services": ["Hospital Visits", "Medical Equipment", "Medicines", "Diagnostic Services", "Nutrition Consultation", "Ambulance", "Doctor Visits", "X-Ray", "Blood Collection"]
}
STANDARD_PLANS = list(SERVICES_MASTER.keys())[:5]
PLAN_DISPLAY_NAMES = {
    "Plan A: Patient Attendant Care": "Patient Care", "Plan B: Skilled Nursing": "Nursing Care",
    "Plan C: Chronic Management": "Chronic Management Care", "Plan D: Elderly Companion": "Elderly Companion Care",
    "Plan E: Maternal & Newborn": "Maternal & Newborn Care", "Plan F: Rehabilitative Care": "Rehabilitative Care",
    "A-la-carte Services": "Other Services"
}
COLUMN_ALIASES = {
    'Serial No.': ['Serial No.', 'serial no', 'sr no', 'sr. no.', 'id'],
    'Ref. No.': ['Ref. No.', 'ref no', 'ref. no.', 'reference no', 'reference number'],
    'Name': ['Name', 'name', 'patient name', 'client name'],
    'Mobile': ['Mobile', 'mobile', 'phone', 'contact'],
    'Location': ['Location', 'location', 'city'], 
    'Address': ['Address', 'address', 'residence'],
    'Gender': ['Gender', 'gender', 'sex'],
    'Age': ['Age', 'age'],
    'Service Required': ['Service Required', 'service required', 'plan'],
    'Sub Service': ['Sub Service', 'sub service', 'sub plan'],
    'Final Rate': ['Final Rate', 'final rate', 'amount', 'total amount'],
    'Unit Rate': ['Rate Agreed (₹)', 'rate agreed', 'unit rate', 'per day rate'],
    'Call Date': ['Call Date', 'call date'],
    'Notes': ['Notes / Remarks', 'notes'],
    'Shift': ['Shift', 'shift'],
    'Recurring': ['Recurring Service', 'recurring'],
    'Period': ['Period', 'period'],
    'Visits': ['Vists', 'visits', 'visit'],
    'Referral Code': ['Referral Code', 'referral code', 'ref code'],
    'Referral Name': ['Referral Name', 'referral name', 'ref name'],
    'Referral Credit': ['Referral Credit', 'referral credit', 'ref credit']
}

def get_base_lists(selected_plan, selected_sub_service):
    master_list = SERVICES_MASTER.get(selected_plan, [])
    if "All" in str(selected_sub_service) and selected_plan in STANDARD_PLANS:
        included_raw = [s for s in master_list if s.lower() != "all"]
    else: included_raw = [x.strip() for x in str(selected_sub_service).split(',')]
    included_clean = sorted(list(set([clean_text(s) for s in included_raw if clean_text(s)])))
    not_included_clean = []
    if selected_plan in STANDARD_PLANS:
        for plan_name in STANDARD_PLANS:
            if plan_name == selected_plan: continue 
            for item in SERVICES_MASTER.get(plan_name, []):
                if item.lower() == "all": continue
                cleaned = clean_text(item)
                if cleaned: not_included_clean.append(cleaned)
    else:
        for item in master_list:
            cleaned = clean_text(item)
            if cleaned and cleaned not in included_clean: not_included_clean.append(cleaned)
    return included_clean, list(set(not_included_clean))

def normalize_columns(df, aliases):
    df.columns = df.columns.astype(str).str.strip()
    for standard_name, possible_aliases in aliases.items():
        if standard_name in df.columns: continue 
        for alias in possible_aliases:
            for df_col in df.columns:
                if df_col.lower() == alias.lower():
                    df.rename(columns={df_col: standard_name}, inplace=True); break 
    return df

def convert_html_to_pdf(source_html):
    result = BytesIO()
    pisa_status = pisa.CreatePDF(source_html, dest=result)
    if pisa_status.err: return None
    return result.getvalue()

# ==========================================
# 4. UI & LOGIC
# ==========================================
st.title("🏥 Vesak Care - Invoice Generator")

abs_logo_path = get_absolute_path(LOGO_FILE)
logo_b64 = get_clean_image_base64(LOGO_FILE)

drive_service = get_drive_service() 
sheet_obj = None 

with st.sidebar:
    st.header("📂 Data Source")
    
    # --- NEW: SYSTEM HEALTH CHECK BUTTON ---
    if st.button("🕵️‍♂️ Scan System Connections", type="primary"):
        run_system_health_check(drive_service, MANUAL_SHEET_ID_25, AGREEMENTS_ROOT_ID, INVOICES_ROOT_ID)
    # ---------------------------------------

    if drive_service: st.success("Connected to Google Drive ✅")
    else: st.error("❌ Not Connected to Google Drive")
    data_source = st.radio("Load Confirmed Sheet via:", ["Upload File", "OneDrive Link"])
    if st.button("🔄 Refresh Data Cache"): st.cache_data.clear(); st.success("Cache cleared!"); st.rerun()

raw_file_obj = None
if data_source == "Upload File":
    uploaded_file = st.sidebar.file_uploader("Upload Excel/CSV", type=['xlsx', 'csv'])
    if uploaded_file: raw_file_obj = uploaded_file
elif data_source == "OneDrive Link":
    current_url = load_config_path(URL_CONFIG_FILE)
    url_input = st.sidebar.text_input("Paste OneDrive/Sharepoint Link:", value=current_url)
    if st.sidebar.button("Load from Link"): save_config_path(url_input, URL_CONFIG_FILE); st.rerun()
    if current_url:
        try: raw_file_obj = robust_file_downloader(current_url); st.sidebar.success("✅ File Downloaded")
        except Exception as e: st.sidebar.error(f"Link Error: {e}")

# --- REINTEGRATED ALL 5 TABS ---
tab1, tab2, tab3, tab4, tab5 = st.tabs(["🧾 Generate Invoice", "🆕 Force New Invoice", "©️ Duplicate Invoice", "🛠 Manage Services", "💰 Nurse Payment"])

# --- COMMON INVOICE UI FUNCTION (Used by Tab 1, 2) ---
def render_invoice_ui(df_main, mode="standard"):
    st.info("📅 Step 1: Select Invoice Date to load the correct Workbook/Sheet")
    global_inv_date = st.date_input("Invoice Date:", value=datetime.date.today(), key=f"global_date_{mode}")
    
    current_wb_obj, current_sheet_obj = get_active_sheet_client(drive_service, global_inv_date)
    df_history_data = get_master_history(f"Vesak_Invoice_{global_inv_date.strftime('%y')}", current_sheet_obj)
    
    if current_sheet_obj: st.sidebar.success(f"Writing to: {current_sheet_obj.title} ✅")
    else: st.sidebar.error("❌ No Active Sheet Selected")

    valid_ref_nos = []
    if not df_history_data.empty and 'Ref. No.' in df_history_data.columns:
        unique_refs = df_main['Ref. No.'].unique()
        for ref in unique_refs:
            is_ended = check_if_service_ended_history(df_history_data, ref)
            if mode == "standard":
                if not is_ended: valid_ref_nos.append(str(ref))
            elif mode == "force_new":
                if is_ended: valid_ref_nos.append(str(ref))
    else:
        if mode == "standard": valid_ref_nos = df_main['Ref. No.'].astype(str).tolist()
    
    df_main['Ref_Clean'] = df_main['Ref. No.'].astype(str).str.strip()
    df_filtered_view = df_main[df_main['Ref_Clean'].isin([str(x).strip() for x in valid_ref_nos])]
    df_filtered_view['Label'] = df_filtered_view['Name'].astype(str) + " (" + df_filtered_view['Mobile'].astype(str) + ")"
    unique_labels = [""] + list(df_filtered_view['Label'].unique())
    selected_label = st.selectbox(f"Select Customer ({mode}):", unique_labels, key=f"sel_{mode}")
    
    if not selected_label: st.info("👈 Please select a customer to proceed."); return

    row = df_filtered_view[df_filtered_view['Label'] == selected_label].iloc[0]
    c_serial, c_ref_no, c_plan = str(row.get('Serial No.', '')).strip(), str(row.get('Ref. No.', '')).strip(), row.get('Service Required', '')
    c_name, c_gender = row.get('Name', ''), row.get('Gender', '')
    try: c_age = str(int(float(row.get('Age', '')))) if not pd.isna(row.get('Age', '')) and row.get('Age', '') != '' else ""
    except: c_age = str(row.get('Age', ''))
    c_addr, c_location, c_mob = row.get('Address', ''), row.get('Location', row.get('Address', '')), row.get('Mobile', '')
    c_ref_code = str(row.get('Referral Code', '')).strip() if not pd.isna(row.get('Referral Code', '')) else ""
    c_ref_name = str(row.get('Referral Name', '')).strip() if not pd.isna(row.get('Referral Name', '')) else ""
    try: c_ref_credit = str(row.get('Referral Credit', '')).strip() if not pd.isna(row.get('Referral Credit', '')) else ""
    except: c_ref_credit = ""
    
    st.divider()
    col1, col2 = st.columns(2)
    with col1:
        st.info(f"**Plan:** {PLAN_DISPLAY_NAMES.get(c_plan, c_plan)}"); st.write(f"**Ref No:** {c_ref_no}")
        default_qty = get_last_billing_qty(df_history_data, c_name, c_mob)
        billing_qty = st.number_input(f"Paid for how many units?", min_value=1, value=default_qty, step=1, key=f"qty_{mode}_{selected_label}")
        
        active_record = get_active_invoice_record(df_history_data, c_ref_no)
        next_sequential_inv = get_next_invoice_number_gsheet(global_inv_date, df_history_data, c_location)
        next_uid = get_next_uid_gsheet(df_history_data)

        conflict_exists, default_inv_num, final_uid = False, next_sequential_inv, next_uid
        
        if mode == "standard":
            if active_record is not None:
                existing_inv_num = str(active_record['Invoice Number'])
                st.warning(f"⚠️ Active Invoice Found: {existing_inv_num}.")
                default_inv_num, final_uid = existing_inv_num, str(active_record.get('UID', ''))
                conflict_exists = True
                chk_overwrite = st.checkbox("Overwrite Invoice", key=f"chk_over_{mode}")
            else:
                st.info(f"ℹ️ Generating New Invoice No: {next_sequential_inv}")
        elif mode == "force_new":
            st.warning("⚠ Generating NEW invoice for existing client.")

        inv_num_input = st.text_input("Invoice No:", value=default_inv_num, key=f"inv_input_{mode}", disabled=True if mode == "standard" and not chk_overwrite and conflict_exists else False)
        
    with col2:
        generated_by = st.text_input("Generated By:", value="Vesak Patient Care", key=f"gen_by_{mode}")
        final_notes = st.text_area("Notes:", value=str(row.get('Notes', '')), key=f"notes_{mode}")

    st.subheader("Referral Information")
    r_col1, r_col2, r_col3 = st.columns(3)
    with r_col1: in_ref_code = st.text_input("Referral Code", value=c_ref_code, disabled=bool(c_ref_code), key=f"ref_c_{mode}")
    with r_col2: in_ref_name = st.text_input("Referral Name", value=c_ref_name, disabled=bool(c_ref_name), key=f"ref_n_{mode}")
    with r_col3: in_ref_credit = st.text_input("Referral Credit", value=c_ref_credit, disabled=bool(c_ref_credit), key=f"ref_cr_{mode}")
    
    st.markdown("---")
    btn_new_disabled, btn_over_visible, btn_agg_disabled, btn_dup_disabled = False, False, True, True
    
    if mode == "standard":
        if conflict_exists:
            if chk_overwrite:
                btn_new_disabled, btn_over_visible, btn_agg_disabled, btn_dup_disabled = True, True, False, True
            else:
                btn_new_disabled, btn_over_visible, btn_agg_disabled, btn_dup_disabled = True, False, True, False
        else:
            btn_new_disabled, btn_over_visible, btn_agg_disabled, btn_dup_disabled = False, False, False, True

    b_col1, b_col2, b_col3, b_col4 = st.columns(4)
    btn_new_clicked, btn_over_clicked = False, False
    
    with b_col1:
        if btn_over_visible:
             if st.button("Overwrite Invoice", type="primary", key=f"btn_ov_{mode}"): btn_over_clicked = True
        else:
             if st.button("New Invoice", type="primary", disabled=btn_new_disabled, key=f"btn_nw_{mode}"): btn_new_clicked = True
            
    with b_col2: btn_nurse = st.button("Nurse Agreement", disabled=btn_agg_disabled, key=f"btn_na_{mode}")
    with b_col3: btn_patient = st.button("Patient/Family Agreement", disabled=btn_agg_disabled, key=f"btn_pa_{mode}")
    with b_col4:
        if st.button("Duplicate Invoice", disabled=btn_dup_disabled, key=f"btn_dp_{mode}"):
            st.session_state.active_tab_simulation = "Duplicate"
            st.toast("✅ Switched to Duplicate Mode. Please Click 'Duplicate Invoice' Tab above.")

    if btn_new_clicked or btn_over_clicked:
        clean_plan = PLAN_DISPLAY_NAMES.get(c_plan, c_plan)
        try: unit_rate_val = float(row.get('Unit Rate', 0))
        except: unit_rate_val = 0.0
        total_billed_amount = unit_rate_val * billing_qty
        p_raw = str(row.get('Period', '')).strip()
        unit_label = "Month" if "month" in p_raw.lower() else "Week" if "week" in p_raw.lower() else "Day"
        details_text = f"Paid for {billing_qty} {unit_label}s" if billing_qty > 1 else f"Paid for {billing_qty} {unit_label}"
        
        invoice_record = {
            "UID": str(final_uid), "Serial No.": str(c_serial), "Ref. No.": str(c_ref_no),
            "Invoice Number": str(inv_num_input), "Date": format_date_with_suffix(global_inv_date), 
            "Generated At": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), 
            "Customer Name": str(c_name), "Age": str(c_age), "Gender": str(c_gender), "Location": str(c_location), 
            "Address": str(c_addr), "Mobile": str(c_mob), "Plan": str(clean_plan), "Shift": str(row.get('Shift', '')),
            "Recurring Service": str(row.get('Recurring', '')), "Period": str(row.get('Period', '')), "Visits": 0, 
            "Amount": float(unit_rate_val), "Notes / Remarks": str(final_notes), "Generated By": str(generated_by), 
            "Amount Paid": float(total_billed_amount), "Details": details_text, 
            "Service Started": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Service Ended": "", 
            "Referral Code": str(in_ref_code), "Referral Name": str(in_ref_name), "Referral Credit": str(in_ref_credit)
        }
        
        html_invoice = f"""<!DOCTYPE html><html><head><style>body {{ font-family: 'Lato', sans-serif; }} .page {{ padding: 40px; }} .header {{ text-align: center; }} </style></head><body><div class="page"><div class="header"><h2>INVOICE: {inv_num_input}</h2></div><p><strong>Customer:</strong> {c_name}</p><p><strong>Amount:</strong> {total_billed_amount}</p><p><strong>Date:</strong> {format_date_with_suffix(global_inv_date)}</p></div></body></html>"""
        inv_pdf_bytes = convert_html_to_pdf(html_invoice)

        save_success = False
        if btn_over_clicked:
            if update_invoice_in_gsheet(invoice_record, current_sheet_obj, default_inv_num):
                st.success(f"✅ Invoice {inv_num_input} Data Overwritten Successfully!")
                save_success = True
        elif btn_new_clicked:
            if mode == "force_new" and active_record is not None:
                mark_service_ended(current_sheet_obj, active_record['Invoice Number'], global_inv_date)
            if save_invoice_to_gsheet(invoice_record, current_sheet_obj):
                st.success(f"✅ Invoice {inv_num_input} Data Created Successfully!")
                save_success = True

        if save_success and inv_pdf_bytes and drive_service:
            # 1. Drive Upload Logic (Robust Folder Handling)
            inv_folder_id = get_target_folder_hierarchy(drive_service, "Invoice", global_inv_date)
            inv_file_name = generate_filename("Invoice", inv_num_input, c_name)
            
            if inv_folder_id:
                existing_inv_id = find_file_in_folder(drive_service, inv_folder_id, inv_file_name)
                if existing_inv_id:
                    if btn_over_clicked:
                        update_drive_file(drive_service, existing_inv_id, inv_pdf_bytes)
                        st.success(f"✅ Drive: Invoice PDF Overwritten.")
                    else:
                        st.warning(f"⚠️ Drive: Invoice PDF exists. Skipping.")
                else:
                    upload_to_drive(drive_service, inv_folder_id, inv_file_name, inv_pdf_bytes)
                    st.success(f"✅ Drive: Invoice PDF Saved.")
            
            # 2. Local Download Logic
            st.download_button("⬇️ Download Invoice PDF Locally", data=inv_pdf_bytes, file_name=inv_file_name, mime="application/pdf")

        if save_success: st.rerun()

    if btn_nurse or btn_patient:
        doc_type = "Nurse" if btn_nurse else "Patient"
        display_type = "NURSE AGREEMENT" if btn_nurse else "PATIENT AGREEMENT"
        html_agreement = f"""<!DOCTYPE html><html><head><style>body {{ font-family: 'Lato', sans-serif; }} .page {{ position: relative; padding: 40px; }} .watermark {{ position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); font-size: 100px; color: #002147; opacity: 0.1; font-weight: bold; z-index: -1; }} .header {{ text-align: center; margin-bottom: 30px; }} .title {{ font-size: 24px; font-weight: bold; text-decoration: underline; color: #002147; }} .content {{ font-size: 14px; line-height: 1.6; text-align: justify; }}</style></head><body><div class="watermark">VESAK</div><div class="page"><div class="header"><img src="data:image/png;base64,{logo_b64}" width="100"><h2>Vesak Care Foundation</h2></div><div class="title">{display_type}</div><br><div class="content"><p><strong>Date:</strong> {format_date_with_suffix(global_inv_date)}</p><p><strong>Ref No:</strong> {c_ref_no}</p><p><strong>Client Name:</strong> {c_name}</p><br><p>This is a placeholder for the {display_type.title()}. Content will be updated later.</p><p>__________________________<br>Authorized Signatory</p></div></div></body></html>"""
        pdf_bytes = convert_html_to_pdf(html_agreement)
        
        if pdf_bytes:
            file_name = generate_filename(doc_type, inv_num_input, c_name)
            
            # 1. Drive Upload
            if drive_service:
                folder_id = get_target_folder_hierarchy(drive_service, doc_type, global_inv_date)
                if folder_id:
                    existing_file_id = find_file_in_folder(drive_service, folder_id, file_name)
                    if existing_file_id:
                         if conflict_exists and chk_overwrite:
                            if update_drive_file(drive_service, existing_file_id, pdf_bytes): st.success(f"✅ Drive: Overwritten {file_name}")
                            else: st.error("Failed to overwrite file.")
                         else: st.warning(f"⚠️ Drive: File exists. Use 'Overwrite'.")
                    else:
                         if upload_to_drive(drive_service, folder_id, file_name, pdf_bytes): st.success(f"✅ Drive: Saved {file_name}")
            
            # 2. Local Download
            st.download_button(f"⬇️ Download {doc_type} Agreement", data=pdf_bytes, file_name=file_name, mime="application/pdf")

if raw_file_obj:
    try:
        # --- FIXED FILE READING LOGIC ---
        is_excel = False
        filename = getattr(raw_file_obj, "name", "downloaded_data.xlsx")
        
        if hasattr(raw_file_obj, 'seek'): raw_file_obj.seek(0)
        if filename.endswith('.xlsx') or isinstance(raw_file_obj, BytesIO):
            is_excel = True
            
        if is_excel: df = pd.read_excel(raw_file_obj, engine='openpyxl')
        else: df = pd.read_csv(raw_file_obj)
            
        df = normalize_columns(df, COLUMN_ALIASES)
        
        # TAB 1 & 2
        with tab1: render_invoice_ui(df, mode="standard")
        with tab2: render_invoice_ui(df, mode="force_new")

        # TAB 3: DUPLICATE (LOCAL DOWNLOAD ONLY)
        with tab3:
            st.header("©️ Duplicate Invoice from History")
            dup_date = st.date_input("New Invoice Date:", value=datetime.date.today(), key="dup_date")
            _, dup_sheet_obj = get_active_sheet_client(drive_service, dup_date)
            hist_df = get_master_history("Master", dup_sheet_obj)
            
            if not hist_df.empty and 'Invoice Number' in hist_df.columns:
                hist_df['Display'] = hist_df['Invoice Number'] + " - " + hist_df['Customer Name']
                selected_dup = st.selectbox("Select Invoice to Duplicate:", hist_df['Display'].unique())
                
                if selected_dup:
                    src_row = hist_df[hist_df['Display'] == selected_dup].iloc[0]
                    dup_inv_no = str(src_row['Invoice Number'])
                    dup_name = str(src_row['Customer Name'])
                    
                    st.info(f"Selected: {dup_name}")
                    
                    # Generate PDFs for Download (NO DRIVE SAVE)
                    # 1. Invoice
                    html_dup_inv = f"""<!DOCTYPE html><html><body><h2>DUPLICATE INVOICE: {dup_inv_no}</h2><p>Customer: {dup_name}</p></body></html>"""
                    pdf_dup_inv = convert_html_to_pdf(html_dup_inv)
                    fname_inv = generate_filename("Invoice", dup_inv_no, dup_name)
                    st.download_button("⬇️ Download Duplicate Invoice PDF", data=pdf_dup_inv, file_name=fname_inv, mime="application/pdf")
                    
                    # 2. Nurse Agreement
                    html_dup_nu = f"""<!DOCTYPE html><html><body><h2>NURSE AGREEMENT</h2><p>Ref: {dup_inv_no}</p></body></html>"""
                    pdf_dup_nu = convert_html_to_pdf(html_dup_nu)
                    fname_nu = generate_filename("Nurse", dup_inv_no, dup_name)
                    st.download_button("⬇️ Download Nurse Agreement PDF", data=pdf_dup_nu, file_name=fname_nu, mime="application/pdf")

                    # 3. Patient Agreement
                    html_dup_pa = f"""<!DOCTYPE html><html><body><h2>PATIENT AGREEMENT</h2><p>Ref: {dup_inv_no}</p></body></html>"""
                    pdf_dup_pa = convert_html_to_pdf(html_dup_pa)
                    fname_pa = generate_filename("Patient", dup_inv_no, dup_name)
                    st.download_button("⬇️ Download Patient Agreement PDF", data=pdf_dup_pa, file_name=fname_pa, mime="application/pdf")
            else:
                st.warning("No History Found.")

        # TAB 4: MANAGE SERVICES
        with tab4:
            st.header("🛠 Service Manager & Calculator")
            ms_plan = st.selectbox("Select Plan:", list(SERVICES_MASTER.keys()))
            ms_sub = st.text_input("Sub-services:", value="All")
            inc, exc = get_base_lists(ms_plan, ms_sub)
            c1, c2 = st.columns(2)
            with c1: 
                st.success(f"✅ Included ({len(inc)})")
                for i in inc: st.write(f"- {i}")
            with c2: 
                st.error(f"❌ Excluded ({len(exc)})")
                for e in exc: st.write(f"- {e}")

        # TAB 5: NURSE PAYMENT
        with tab5:
            st.header("💰 Nurse Payment Update")
            pay_sheet_date = st.date_input("Load Sheet Date:", value=datetime.date.today(), key="pay_sheet_date")
            _, pay_sheet_obj = get_active_sheet_client(drive_service, pay_sheet_date)
            if pay_sheet_obj:
                pay_inv_no = st.text_input("Enter Invoice Number to Pay:")
                pay_amount = st.number_input("Nurse Payment Amount (₹):", min_value=0.0)
                if st.button("Update Payment"):
                    if update_nurse_payment(pay_sheet_obj, pay_inv_no, pay_amount): st.success("✅ Payment Updated!")
                    else: st.error("❌ Failed to update.")
            
    except Exception as e: st.error(f"Error reading file: {e}")
