# helpers_utils.py
"""
helpers_utils.py

Common helper utilities for Vesak Invoice app:
- ID normalization, referral cleaning
- Billing helpers (get_base_lists, construct_description_html, construct_amount_html)
- Filename generation, column alias normalization
- Small UI helpers: infer_role, render_invoice_ui (rich Tab1 implementation)
- GSpread helpers used by render_invoice_ui (local, safe)
"""

from typing import Tuple, List, Dict, Any, Optional
import datetime
import re
import os
import base64
from io import BytesIO

import pandas as pd
import streamlit as st

# try import gspread and google auth tools; if not available we'll surface runtime errors in the UI
try:
    import gspread
    from google.oauth2.service_account import Credentials
except Exception:
    gspread = None
    Credentials = None

# ---------------------------
# CONSTANTS
# ---------------------------
SHEET_HEADERS = [
    "UID", "Serial No.", "Ref. No.", "Invoice Number", "Date", "Generated At",
    "Customer Name", "Age", "Gender", "Location", "Address", "Mobile",
    "Plan", "Shift", "Recurring Service", "Period", "Visits", "Amount",
    "Notes / Remarks", "Generated By", "Amount Paid", "Details",
    "Service Started", "Service Ended", "Referral Name", "Referral Code",
    "Referral Credit", "Net Amount", "Nurse Payment", "Paid for", "Earnings",
    "Nurse Name", "Nurse Name (Extra)", "Nurse Note"
]

# ---------------------------
# CONFIG LOADER
# ---------------------------
SYSTEM_CONFIG_FILE = "system_config.json"


def load_system_config() -> dict:
    try:
        if os.path.exists(SYSTEM_CONFIG_FILE):
            with open(SYSTEM_CONFIG_FILE, "r", encoding="utf-8") as f:
                import json
                return json.load(f)
    except Exception:
        pass
    return {}


# ---------------------------
# GSPREAD CLIENT (fallback from st.secrets)
# ---------------------------
@st.cache_resource
def get_gspread_client() -> Optional[Any]:
    """
    Create a gspread client from st.secrets if available.
    Returns None if not configured.
    """
    if gspread is None or Credentials is None:
        return None
    try:
        # Expecting service account info inside st.secrets["connections"]["gsheets"]
        if "connections" in st.secrets and "gsheets" in st.secrets["connections"]:
            s_info = st.secrets["connections"]["gsheets"]
            # Some environments store private_key with escaped newlines; fix that
            if s_info.get("private_key") and "\\n" in s_info.get("private_key"):
                s_info["private_key"] = s_info["private_key"].replace("\\n", "\n")
            creds = Credentials.from_service_account_info(s_info, scopes=[
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/drive"
            ])
            return gspread.authorize(creds)
    except Exception as e:
        st.warning(f"gspread init failed: {e}")
    return None


def extract_id_from_url(url: str) -> Optional[str]:
    """Extract Google Sheets id from url; returns None when not found."""
    if not url:
        return None
    m = re.search(r"/d/([a-zA-Z0-9-_]+)", url)
    if m:
        return m.group(1)
    return None


# ---------------------------
# ID & TEXT CLEANING
# ---------------------------
def normalize_id(val: Any) -> str:
    """Normalize id to integer-like string (no decimals) or empty string."""
    if val is None:
        return ""
    try:
        if pd.isna(val):
            return ""
    except Exception:
        pass
    s_val = str(val).strip()
    if s_val == "" or s_val.lower() == "nan":
        return ""
    try:
        # handle floats like 1.0
        return str(int(float(s_val)))
    except Exception:
        return s_val


def clean_referral_field(val: Any) -> str:
    """Normalize referral fields (remove 'nan', 'none', empty)."""
    try:
        if pd.isna(val):
            return ""
    except Exception:
        pass
    s_val = str(val).strip()
    if s_val.lower() in ("nan", "none", ""):
        return ""
    return s_val


# ---------------------------
# CACHED EXCLUSION LIST
# ---------------------------
def get_cached_exclusion_list(master_id: str, month_str: str) -> Tuple[List[str], List[str]]:
    """
    Returns (present_refs, ended_refs) for the given master workbook and month.
    Uses gspread to read backup monthly sheet (if any) for cached keys.
    This function is designed to be robust: if the sheet is missing or client invalid,
    it returns empty lists.
    """
    present_refs: List[str] = []
    ended_refs: List[str] = []
    client = get_gspread_client()
    if client is None or not master_id:
        return present_refs, ended_refs
    try:
        wb = client.open_by_key(master_id)
        try:
            ws = wb.worksheet(month_str)
            data = ws.get_all_records()
            df = pd.DataFrame(data)
            if df.empty:
                return present_refs, ended_refs
            # normalize
            if "Ref. No." in df.columns and "Serial No." in df.columns:
                df['Ref_Norm'] = df['Ref. No.'].apply(normalize_id)
                df['Ser_Norm'] = df['Serial No.'].apply(normalize_id)
                for _, r in df.iterrows():
                    k = f"{str(r.get('Ref_Norm','')).strip()}-{str(r.get('Ser_Norm','')).strip()}"
                    present_refs.append(k)
                    if str(r.get('Service Ended', '')).strip():
                        ended_refs.append(k)
        except Exception:
            # missing worksheet -> return empties
            pass
    except Exception:
        pass
    return present_refs, ended_refs


# ---------------------------
# FILENAME GENERATOR
# ---------------------------
def generate_filename(doc_type: str, invoice_no: str, customer_name: str) -> str:
    prefix_map = {
        "Invoice": "IN",
        "Nurse": "NU",
        "Patient": "PA",
        "Caregiver Service Agreement": "CSA",
        "Client / Family Agreement": "CFA",
        "Warning Letter": "WL",
    }
    prefix = prefix_map.get(doc_type, "DOC")
    clean_name = re.sub(r'[^a-zA-Z0-9]', '-', str(customer_name)).upper().strip('-')
    clean_invoice = str(invoice_no).strip()
    return f"{prefix}-{clean_invoice}-{clean_name}.pdf"


# ---------------------------
# SERVICE / BILLING LOGIC
# ---------------------------
def get_base_lists(selected_plan: str, selected_sub_service: str):
    """
    Returns (included_clean, not_included_clean)
    Basic mapping: extendable for your full mapping.
    """
    SERVICES_MASTER = {
        "Plan A: Patient Attendant Care": ["All", "Basic Care", "Feeding & Oral Hygiene", "Mobility Support"],
        "Plan B: Skilled Nursing": ["All", "IV Therapy", "Medication Management", "Wound Care"],
        "Plan C: Chronic Management": ["All", "Chronic Care", "Dementia Support"],
        "Plan D: Elderly Companion": ["All", "Companionship", "Fall Prevention"],
        "Plan E: Maternal & Newborn": ["All", "Postnatal Care", "Newborn Care"],
        "Plan F: Rehabilitative Care": ["Therapeutic Massage", "Exercise Therapy", "Neuro Rehab"],
        "A-la-carte Services": ["Hospital Visits", "Medicines", "Diagnostics", "Doctor Visit"],
    }
    base_plan = selected_plan
    # try approximate match
    for k in SERVICES_MASTER.keys():
        if k in selected_plan:
            base_plan = k
            break
    master_list = SERVICES_MASTER.get(base_plan, [])
    if "All" in str(selected_sub_service) and "All" in master_list:
        included_raw = [s for s in master_list if s.lower() != "all"]
    else:
        included_raw = [x.strip() for x in str(selected_sub_service).split(',') if x.strip()]
    included_clean = sorted(list(set([s.strip() for s in included_raw if s and s.strip()])))
    not_included_clean = []
    for plan_name, items in SERVICES_MASTER.items():
        if plan_name == base_plan:
            continue
        for it in items:
            if it.lower() == "all":
                continue
            if it.strip() not in included_clean:
                not_included_clean.append(it.strip())
    return included_clean, list(set(not_included_clean))


def construct_description_html(row: dict) -> str:
    shift_raw = str(row.get('Shift', '')).strip()
    period_raw = str(row.get('Period', '')).strip()
    shift_map = {"12-hr Day": "12 Hours - Day", "12-hr Night": "12 Hours - Night", "24-hr": "24 Hours"}
    shift_str = shift_map.get(shift_raw, shift_raw)
    time_suffix = " (Time)" if "12" in shift_str else ""
    return f"""<div style="margin-top: 4px;"><div style="font-size: 12px; color: #4a4a4a; font-weight: bold;">{shift_str}{time_suffix}</div><div style="font-size: 10px; color: #777; font-style: italic; margin-top: 2px;">{period_raw}</div></div>"""


def construct_amount_html(row: dict, billing_qty: int) -> str:
    try:
        unit_rate = float(row.get('Unit Rate', row.get('Amount', 0) or 0))
    except Exception:
        unit_rate = 0.0
    try:
        visits_needed = int(float(row.get('Visits', 0)))
    except Exception:
        visits_needed = 0

    p_raw_check = str(row.get('Period', '')).strip()
    p_check_lower = p_raw_check.lower()
    shift_raw_check = str(row.get('Shift', '')).strip()
    shift_check_lower = shift_raw_check.lower()

    if "per visit" in shift_check_lower:
        details_text = f"Paid for {billing_qty} Visit" if billing_qty == 1 else f"Paid for {billing_qty} Visits"
    elif "daily" in p_check_lower:
        if billing_qty == 1:
            details_text = f"Paid for {billing_qty} Day"
        elif billing_qty % 7 == 0:
            weeks_val = int(billing_qty / 7)
            details_text = f"Paid for {weeks_val} Week" if weeks_val == 1 else f"Paid for {weeks_val} Weeks"
        else:
            details_text = f"Paid for {billing_qty} Days"
    elif "monthly" in p_check_lower:
        details_text = f"Paid for {billing_qty} Month" if billing_qty == 1 else f"Paid for {billing_qty} Months"
    elif "weekly" in p_check_lower:
        details_text = f"Paid for {billing_qty} Week" if billing_qty == 1 else f"Paid for {billing_qty} Weeks"
    else:
        details_text = f"Paid for {billing_qty} {p_raw_check}"

    billing_note = ""
    is_per_visit = "per visit" in shift_check_lower

    if is_per_visit:
        if visits_needed > 1 and billing_qty == 1:
            billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif billing_qty >= visits_needed:
            billing_note = f"Paid for {visits_needed} Visits."
        elif visits_needed == 1:
            billing_note = "Paid for 1 Visit."
        elif billing_qty < visits_needed:
            billing_note = f"Next Bill will be Generated after {billing_qty} Visits."
        else:
            billing_note = details_text
    elif "month" in p_check_lower or "week" in p_check_lower:
        base_unit = "Month" if "month" in p_check_lower else "Week"
        plural_unit = base_unit + "s" if billing_qty > 1 else base_unit
        if visits_needed > 1 and billing_qty == 1:
            billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif visits_needed > billing_qty:
            billing_note = f"Next Bill will be Generated after {billing_qty} {plural_unit}."
        else:
            billing_note = details_text
    elif "daily" in p_check_lower:
        if 1 < visits_needed < 6 and billing_qty == 1:
            billing_note = "Next Billing will be generated after the Payment to Continue the Service."
        elif billing_qty >= visits_needed:
            billing_note = f"Paid for {visits_needed} Days."
        elif visits_needed == 1:
            billing_note = "Paid for 1 Day."
        elif billing_qty < visits_needed:
            billing_note = f"Next Bill will be Generated after {billing_qty} Days."
        else:
            billing_note = details_text
    else:
        billing_note = details_text

    total_amount = unit_rate * billing_qty
    shift_map = {"12-hr Day": "12 Hours - Day", "12-hr Night": "12 Hours - Night", "24-hr": "24 Hours"}
    shift_display = shift_map.get(shift_raw_check, shift_raw_check)
    if "12" in shift_display and "Time" not in shift_display:
        shift_display += " (Time)"

    period_display = p_raw_check
    if "month" in p_check_lower:
        period_display = "Month"
    elif "week" in p_check_lower:
        period_display = "Week"
    elif "daily" in p_check_lower:
        period_display = "Day"

    unit_rate_str = "{:,.0f}".format(unit_rate)
    total_amount_str = "{:,.0f}".format(total_amount)

    if is_per_visit:
        rate_line_html = f"{shift_display} = <b>₹ {unit_rate_str}</b>"
    else:
        rate_line_html = f"{shift_display} / {period_display} = <b>₹ {unit_rate_str}</b>"

    paid_for_text = details_text

    return f"""
    <div style="text-align: right; font-size: 13px; color: #555;">
        <div style="margin-bottom: 4px;">{rate_line_html}</div>
        <div style="color: #CC4E00; font-weight: bold; font-size: 14px; margin: 2px 0;">X</div>
        <div style="font-weight: bold; font-size: 13px; margin: 2px 0; color: #333;">{paid_for_text}</div>
        <div style="border-bottom: 1px solid #ccc; width: 100%; margin: 6px 0;"></div>
        <div style="display: flex; justify-content: flex-end; align-items: center; gap: 8px;">
            <span style="font-size: 13px; font-weight: 800; color: #002147; text-transform: uppercase;">TOTAL - </span>
            <span style="font-size: 16px; font-weight: bold; color: #000;">Rs. {total_amount_str}</span>
        </div>
        <div style="font-size: 10px; color: #666; font-style: italic; margin-top: 6px;">{billing_note}</div>
    </div>
    """


# ---------------------------
# Small UI helpers
# ---------------------------
def infer_role(plan_name: str) -> tuple:
    """
    Returns (default_role, is_locked) - minimal logic
    """
    if not plan_name:
        return "Nurse/Caregiver/Attendant", False
    if "Plan B" in plan_name:
        return "Nurse", True
    if "Plan F" in plan_name:
        return "Physiotherapist", True
    if "A-la-carte" in plan_name:
        return "Attendant", True
    return "Nurse/Caregiver/Attendant", False


def get_logo_b64(logo_path: str = "logo.png") -> str:
    """
    Return base64 string of image if available, else empty string.
    """
    try:
        if os.path.exists(logo_path):
            with open(logo_path, "rb") as f:
                return base64.b64encode(f.read()).decode("utf-8")
    except Exception:
        pass
    return ""


def format_date_with_suffix(d: datetime.date) -> str:
    """
    Format a date like '3rd Jan 2026' used in preview. Safe fallback.
    """
    try:
        if not isinstance(d, (datetime.date, datetime.datetime)):
            d = pd.to_datetime(str(d)).date()
        day = d.day
        if 4 <= day <= 20 or 24 <= day <= 30:
            suffix = "th"
        else:
            suffix = ["st", "nd", "rd"][day % 10 - 1]
        return d.strftime(f"%d{suffix} %b %Y")
    except Exception:
        try:
            return str(d)
        except:
            return ""


# ---------------------------
# HTML/Invoice rendering (rich Tab 1)
# This is your original, verbatim render_invoice_ui function
# Source: Invoice_Design_Tab1.txt uploaded by you. (We've adapted helper refs above.)
# ---------------------------
def render_invoice_ui(df_main, mode="standard"):
    # ========================================================
    # ⭐ RESET TRIGGER CHECK (SOLVES THE STREAMLIT ERROR)
    # ========================================================
    # This block executes BEFORE the widgets are drawn.
    # It checks if the previous run requested a reset.
    if st.session_state.get(f"trigger_reset_{mode}", False):
        st.session_state[f"inv_d_{mode}"] = datetime.date.today()
        # Reset overwrite checkbox key if it exists
        if f"ow_{mode}" in st.session_state:
            st.session_state[f"ow_{mode}"] = False
        # Consume the trigger
        st.session_state[f"trigger_reset_{mode}"] = False

    # --------------------------------------------------------

    client = get_gspread_client()
    config = load_system_config()
    master_id = extract_id_from_url(config.get("master_sheet_url"))

    if not master_id or not client:
        st.error("❌ Master Workbook not linked in Sidebar Settings.")
        return

    # --- FILTER SECTION ---
    st.subheader("1. Select Customer")

    # ⭐ CHANGE: NEW CUSTOMER vs EXISTING CUSTOMER TOGGLE
    try:
        # streamlit < 1.20 may not have st.toggle; use checkbox fallback
        toggle_fn = getattr(st, "toggle", None)
        if callable(toggle_fn):
            show_existing = st.toggle("📂 Switch List: 🆕 New Customers ⇄ 📂 Existing Customers", value=False)
        else:
            show_existing = st.checkbox("📂 Switch List: 🆕 New Customers ⇄ 📂 Existing Customers (toggle)", value=False)
    except Exception:
        show_existing = st.checkbox("📂 Switch List: 🆕 New Customers ⇄ 📂 Existing Customers (toggle)", value=False)

    # Auto-set Overwrite checkbox based on toggle
    st.session_state[f"ow_{mode}"] = show_existing

    use_filters = st.checkbox("🔍 Enable Search Filters (Date/Location)", key=f"use_filt_{mode}")

    df_view = df_main.copy() if df_main is not None else pd.DataFrame()

    # Filter logic
    if use_filters and not df_view.empty:
        col_filt1, col_filt2 = st.columns(2)
        with col_filt1:
            filter_date = st.date_input("Filter Date (Search by Date):", value=datetime.date.today(), key=f"f_date_{mode}")
        with col_filt2:
            unique_locs = ["All"] + sorted(list(df_main['Location'].astype(str).unique())) if 'Location' in df_main.columns else ["All"]
            filter_loc = st.selectbox("Filter Location:", unique_locs, key=f"f_loc_{mode}")

        if 'Call Date' in df_view.columns:
            df_view['TempDate'] = pd.to_datetime(df_view['Call Date'], errors='coerce').dt.date
            df_view = df_view[df_view['TempDate'] == filter_date]

        if filter_loc != "All":
            df_view = df_view[df_view['Location'].astype(str) == filter_loc]

    # --- CRITICAL POINT 2: EXCLUSION LOGIC (CACHED) ---
    current_mmm_yy = datetime.date.today().strftime("%b-%y")

    # UNPACK TUPLE: Get both 'Present' and 'Ended' lists
    present_refs, ended_refs = get_cached_exclusion_list(master_id, current_mmm_yy)

    # Ensure required columns exist
    if df_view is None or df_view.empty:
        df_view = pd.DataFrame(columns=df_main.columns if df_main is not None else [])

    if 'Ref. No.' not in df_view.columns:
        df_view['Ref. No.'] = ""
    if 'Serial No.' not in df_view.columns:
        df_view['Serial No.'] = ""
    if 'Mobile' not in df_view.columns:
        df_view['Mobile'] = ""
    if 'Name' not in df_view.columns:
        df_view['Name'] = ""
    if 'Location' not in df_view.columns:
        df_view['Location'] = ""

    df_view['Ref_Norm_View'] = df_view['Ref. No.'].apply(normalize_id)
    df_view['Ser_Norm_View'] = df_view['Serial No.'].apply(normalize_id)
    df_view['Unique_Key'] = df_view['Ref_Norm_View'] + "-" + df_view['Ser_Norm_View']

    if show_existing:
        # Switch ON: Show Existing Customers
        # CRITICAL: Exclude those with "Service Ended" data
        if present_refs:
            active_keys = set(present_refs) - set(ended_refs)
            df_view = df_view[df_view['Unique_Key'].isin(active_keys)]
        else:
            df_view = pd.DataFrame(columns=df_view.columns)  # Empty if no history
    else:
        # Switch OFF: Show New Customers (Not in History)
        if present_refs:
            df_view = df_view[~df_view['Unique_Key'].isin(present_refs)]

    # cleanup helper cols
    if 'Ref_Norm_View' in df_view.columns:
        df_view = df_view.drop(columns=['Ref_Norm_View'])
    if 'Ser_Norm_View' in df_view.columns:
        df_view = df_view.drop(columns=['Ser_Norm_View'])
    if 'Unique_Key' in df_view.columns:
        df_view = df_view.drop(columns=['Unique_Key'])

    # Prepare label
    df_view['Ref_Clean'] = df_view['Ref. No.'].astype(str).str.strip()
    df_view['Label'] = df_view.get('Name', df_view.get('Customer Name', '')).astype(str) + " (" + df_view['Mobile'].astype(str) + ")"

    if df_view.empty:
        if show_existing:
            st.info("📂 No existing invoices found for this month.")
        else:
            st.success("✅ All customers have invoices! Switch toggle to view existing.")
        return

    selected_label = st.selectbox(f"Select Customer ({mode}):", [""] + list(df_view['Label'].unique()), key=f"sel_{mode}")

    if not selected_label:
        return

    row = df_view[df_view['Label'] == selected_label].iloc[0]

    c_ref = normalize_id(row.get('Ref. No.', '')).strip()
    c_serial = normalize_id(row.get('Serial No.', '')).strip()
    c_mob = normalize_id(row.get('Mobile', '')).strip()
    c_name = row.get('Name', row.get('Customer Name', ''))
    c_plan = row.get('Service Required', row.get('Plan', ''))
    c_age = str(row.get('Age', ''))
    c_gender = str(row.get('Gender', ''))
    c_loc = str(row.get('Location', ''))
    c_addr = str(row.get('Address', ''))
    c_shift = str(row.get('Shift', ''))
    c_rec = str(row.get('Recurring Service', ''))
    c_period = str(row.get('Period', ''))
    c_visits = str(row.get('Visits', ''))

    c_ref_code = clean_referral_field(row.get('Referral Code', ''))
    c_ref_name = clean_referral_field(row.get('Referral Name', ''))
    raw_credit = row.get('Referral Credit', '')
    c_ref_credit = str(int(float(raw_credit))) if str(raw_credit).replace('.', '', 1).isdigit() else clean_referral_field(raw_credit)

    # --- INVOICE DATE SECTION (NEW) ---
    st.divider()
    st.subheader("2. Invoice Details")

    # Overwrite Checkbox (Moved up to control Disabled state)
    chk_overwrite = st.checkbox("Overwrite Existing Invoice", key=f"ow_{mode}")

    # --- INVOICE CALCULATION LOGIC ---
    inv_final = ""
    default_date = datetime.date.today()
    default_qty = 1

    # UPDATED NOTE LOGIC
    val_notes = row.get('Notes', '')
    default_notes = "" if pd.isna(val_notes) or str(val_notes).strip().lower() == 'nan' else str(val_notes)

    if "Plan F" in str(c_plan):
        disclaimer_text = "All medical equipment, consumables (gloves, cotton, medicines, oils, tapes), and assistive devices (walkers, beds, weights/bands) required for the execution of these duties must be provided by the Client. The Caregiver/Therapist provides expertise and labor only."
        if default_notes:
            default_notes += f"\n\n{disclaimer_text}"
        else:
            default_notes = disclaimer_text

    conflict_exists = False
    existing_row_idx = None

    mmm_yy = default_date.strftime("%b-%y")

    sheet_obj = None
    try:
        wb_save = client.open_by_key(master_id)
        try:
            sheet_obj = wb_save.worksheet(mmm_yy)
        except Exception:
            sheet_obj = wb_save.add_worksheet(title=mmm_yy, rows=1000, cols=34)
            sheet_obj.append_row(SHEET_HEADERS)
    except Exception as e:
        st.error(f"Connection Error: {e}")
        return

    if sheet_obj:
        try:
            master_records = sheet_obj.get_all_records()
            df_history = pd.DataFrame(master_records)
        except Exception:
            df_history = pd.DataFrame()
        if not df_history.empty:
            df_history['Ref_Norm'] = df_history['Ref. No.'].apply(lambda x: normalize_id(x).strip())
            df_history['Ser_Norm'] = df_history['Serial No.'].apply(lambda x: normalize_id(x).strip())

            match_mask = (
                (df_history['Ref_Norm'].astype(str) == str(c_ref)) &
                (df_history['Ser_Norm'].astype(str) == str(c_serial))
            )

            existing_matches = df_history[match_mask]

            if not existing_matches.empty:
                conflict_exists = True
                last_match = existing_matches.iloc[-1]

                inv_final = str(last_match.get('Invoice Number', ''))

                hist_note = str(last_match.get('Notes / Remarks', '')).strip()
                if hist_note:
                    default_notes = hist_note

                # Paid Units detection
                raw_paid_val = last_match.get('Paid for', '')
                try:
                    if raw_paid_val and str(raw_paid_val).strip().isdigit():
                        default_qty = int(str(raw_paid_val).strip())
                    else:
                        hist_details = str(last_match.get('Details', ''))
                        match_qty = re.search(r'Paid for\s*(\d+)', hist_details, re.IGNORECASE)
                        if match_qty:
                            default_qty = int(match_qty.group(1))
                except Exception:
                    pass

                # Date parsing (best-effort)
                try:
                    hist_date_str = str(last_match.get('Date', ''))
                    clean_date_str = re.sub(r'(\d+)(st|nd|rd|th)', r'\1', hist_date_str)
                    try:
                        default_date = datetime.datetime.strptime(clean_date_str, "%b. %d %Y").date()
                    except Exception:
                        # fallback: try general parse
                        default_date = pd.to_datetime(clean_date_str, errors='coerce').date()
                except Exception:
                    pass

                try:
                    idx = existing_matches.index.tolist()[-1]
                    existing_row_idx = idx + 2
                except Exception:
                    existing_row_idx = None
            else:
                default_qty = 1
                conflict_exists = False
        else:
            default_qty = 1
            conflict_exists = False
    else:
        default_qty = 1
        conflict_exists = False

    if not conflict_exists:
        raw_loc = str(row.get('Location', '')).lower().strip()
        loc_code = "MUM" if "mumbai" in raw_loc else "PUN"
        target_month = default_date.month
        target_year = default_date.year

        max_existing_seq = 0
        if not df_history.empty and 'Invoice Number' in df_history.columns:
            inv_series = df_history['Invoice Number'].dropna().astype(str)
            for existing_inv in inv_series:
                clean_inv = existing_inv.strip()
                match = re.search(r'^([A-Z]{3})-(\d{2})(\d{2})(\d{4})-(\d+)$', clean_inv)
                if match:
                    f_loc = match.group(1)
                    f_month = int(match.group(3))
                    f_year = int(match.group(4))
                    f_seq = int(match.group(5))
                    if f_loc == loc_code and f_month == target_month and f_year == target_year:
                        if f_seq > max_existing_seq:
                            max_existing_seq = f_seq
        next_seq = max_existing_seq + 1
        date_str_final = default_date.strftime('%d%m%Y')
        inv_final = f"{loc_code}-{date_str_final}-{next_seq:03d}"

    # ================= UI SECTION =================
    col_inv1, col_inv2 = st.columns(2)

    with col_inv1:
        inv_date_val = st.date_input("Invoice Date:", value=default_date, key=f"inv_d_{mode}")

    with col_inv2:
        is_inv_disabled = True if (conflict_exists and not chk_overwrite) else False
        inv_input = st.text_input("Invoice Number", value=inv_final, disabled=is_inv_disabled, key=f"inv_n_{mode}")

    st.write(f"**Plan:** {c_plan} | **Ref:** {c_ref} | **Serial:** {c_serial}")

    if conflict_exists:
        if chk_overwrite:
            st.info(f"✅ Overwrite is ON – changes will update Invoice #{inv_final}")
        else:
            st.warning(f"⚠️ Customer exists (Ref: {c_ref}, Serial: {c_serial}). Tick 'Overwrite' to Update.")

    col3, col4 = st.columns(2)

    with col3:
        billing_qty = st.number_input("Paid Units:", min_value=1, value=default_qty, key=f"qty_{mode}_{selected_label}")
        notes = st.text_area("Notes:", value=default_notes, key=f"note_{mode}")

    with col4:
        gen_by_input = st.text_input("Generated By:", value="", placeholder="Leave blank for Default", key=f"gen_{mode}")
        gen_by_to_save = (gen_by_input if gen_by_input.strip() else "Vesak Patient Care")

    st.subheader("Services")
    inc_list, exc_list = get_base_lists(str(c_plan), row.get('Sub Service', 'All'))

    sc1, sc2 = st.columns(2)

    with sc1:
        st.text_area("Included", ", ".join(inc_list), disabled=True)

    with sc2:
        exc_final = st.multiselect("Excluded (Click X to remove):", options=exc_list, default=exc_list, key=f"exc_{mode}_{c_ref}")
        exc_text_for_pdf = ", ".join(exc_final)

    disable_ref = False
    if c_ref_name and c_ref_code and c_ref_credit:
        disable_ref = True
    if chk_overwrite:
        disable_ref = False

    with st.expander("🎁 Referral Details", expanded=True):
        cr1, cr2, cr3 = st.columns(3)
        with cr1:
            ref_name_input = st.text_input("Referral Name", value=c_ref_name, disabled=disable_ref, key=f"rn_{mode}")
        with cr2:
            ref_code_input = st.text_input("Referral Code", value=c_ref_code, disabled=disable_ref, key=f"rc_{mode}")
        with cr3:
            ref_credit_input = st.text_input("Referral Credit", value=c_ref_credit, disabled=disable_ref, key=f"rcred_{mode}")

    # PREVIEW SECTION - GENERATE HTML LIVE
    preview_rate = float(row.get('Unit Rate', 0) or 0)
    preview_total = preview_rate * int(billing_qty)
    preview_date_str = format_date_with_suffix(inv_date_val)
    preview_file_name = generate_filename("Invoice", inv_input, c_name)

    desc_col_html = construct_description_html(row)
    amount_col_html = construct_amount_html(row, int(billing_qty))

    pdf_display_plan = str(c_plan)
    sub_srv_txt = str(row.get('Sub Service', '')).strip()

    if pdf_display_plan == "Plan A: Patient Attendant Care":
        pdf_display_plan = "Patient Care Service"
    elif pdf_display_plan == "Plan B: Skilled Nursing":
        pdf_display_plan = "Nurse Service"
    elif pdf_display_plan == "Plan C: Chronic Management":
        pdf_display_plan = "Chronic and Holistic Healthcare Service"
    elif pdf_display_plan == "Plan D: Elderly Companion":
        pdf_display_plan = "Elderly and Well-being Care"
    elif pdf_display_plan == "Plan E: Maternal & Newborn":
        pdf_display_plan = "Maternal & Newborn - Support for Women during and after Pregnancy"
    elif "Plan F" in pdf_display_plan:
        pdf_display_plan = f"Rehabilitative Care for {sub_srv_txt}"
    elif "A-la-carte" in pdf_display_plan:
        pdf_display_plan = f"Other Service - {sub_srv_txt}"

    clean_plan = pdf_display_plan

    inc_html = "".join([f'<li class="mb-1 text-xs text-gray-700">{item}</li>' for item in inc_list])
    exc_html = "".join([f'<li class="mb-1 text-[10px] text-gray-500">{item}</li>' for item in exc_final])

    notes_section = ""
    if notes:
        notes_section = f"""<div class="mt-6 p-4 bg-gray-50 border border-gray-100 rounded"><h4 class="font-bold text-vesak-navy text-xs mb-1">NOTES:</h4><p class="text-xs text-gray-600 whitespace-pre-wrap">{notes}</p></div>"""

    logo_b64 = get_logo_b64()

    # HTML TEMPLATE (Tailwind + html2pdf)
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script>
        tailwind.config = {{
            theme: {{
                extend: {{
                    colors: {{ vesak: {{ navy: '#002147', gold: '#C5A065', orange: '#CC4E00' }} }},
                    fontFamily: {{ serif: ['"Playfair Display"', 'serif'], sans: ['"Lato"', 'sans-serif'] }}
                }}
            }}
        }}
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;600;700&display=swap');
        body {{ font-family: 'Lato', sans-serif; background: #f0f0f0; margin: 0; }}
        .invoice-page {{ position: relative; background: white; width: 210mm; height: 297mm; padding: 30px; padding-bottom: 120px; overflow: hidden; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.05); display: flex; flex-direction: column; margin-left: auto; margin-right: auto; }}
        main {{ flex: none; }}
        footer {{ position: absolute; bottom: 7mm; left: 30px; right: 30px; text-align: center; }}
        .watermark-container {{ position: fixed; top: 148.5mm; left: 50%; transform: translateX(-50%) translateY(-50%); pointer-events: none; z-index: 0; }}
        .watermark-text {{ font-family: 'Playfair Display', serif; font-size: 80px; font-weight: 800; color: rgba(0, 33, 71, 0.04); letter-spacing: 0.25em; }}
        @media print {{
            body {{ background: white; -webkit-print-color-adjust: exact; }}
            .invoice-page {{ width: 210mm; height: 297mm; padding: 20px; padding-bottom: 90px; box-shadow: none; }}
            footer {{ bottom: 7mm; width: calc(100% - 40px); }}
            .no-print {{ display: none !important; }}
            .watermark-container {{ opacity: 0.04 !important; }}
        }}
    </style>
</head>
<body class="py-10">
    <div class="max-w-[210mm] mx-auto mb-6 flex justify-end gap-3 no-print px-4">
        <button onclick="window.print()" class="bg-gray-600 text-white px-5 py-2 rounded shadow hover:bg-gray-800 transition font-bold text-xs uppercase tracking-widest">
            <i class="fas fa-print mr-2"></i> Print / Save Vector PDF
        </button>
        <button onclick="generatePDF()" class="bg-vesak-navy text-white px-6 py-2 rounded shadow hover:bg-vesak-gold transition font-bold text-xs uppercase tracking-widest">
            <i class="fas fa-download mr-2"></i> Download PDF
        </button>
    </div>

    <div class="invoice-page" id="invoice-content">
        <div class="watermark-container">
            <img src="data:image/png;base64,{logo_b64}" style="display:block; margin:0; padding:0; width:300px; opacity:0.04;">
            <div class="watermark-text mt-4">VESAK</div>
        </div>

        <header class="relative z-10 w-full mb-10">
            <div class="flex justify-between items-start border-b border-gray-100 pb-6">
                <div class="flex items-center gap-5">
                    <img src="data:image/png;base64,{logo_b64}" class="w-20 h-auto">
                    <div>
                        <h1 class="font-serif text-2xl font-bold text-vesak-navy tracking-wide leading-none mb-2">
                            Vesak Care <span class="text-vesak-gold font-normal">Foundation</span>
                        </h1>
                        <div class="flex flex-col text-xs text-gray-500 font-light tracking-wide space-y-0.5">
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Web</span> vesakcare.com</span>
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Email</span> vesakcare@gmail.com</span>
                            <span><span class="font-bold text-vesak-gold uppercase w-12 inline-block">Phone</span> +91 7777 000 878</span>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <span class="block font-serif text-3xl text-gray-200 tracking-widest mb-2">INVOICE</span>
                    <div class="text-xs text-vesak-navy">
                        <div class="mb-1"><span class="text-gray-400 uppercase tracking-wider text-[10px] mr-2">Date</span> <b>{preview_date_str}</b></div>
                        <div><span class="text-gray-400 uppercase tracking-wider text-[10px] mr-2">No.</span> <b>{inv_input}</b></div>
                    </div>
                </div>
            </div>
        </header>

        <main class="flex-grow relative z-10">
            
            <div class="flex mb-10 bg-gray-50 border-l-4 border-vesak-navy">
                <div class="w-1/2 p-4 border-r border-gray-200">
                    <div class="text-[10px] font-bold text-vesak-gold uppercase mb-1">Billed To</div>
                    <div class="text-lg font-bold text-vesak-navy">{c_name}</div>
                    <div class="flex gap-4 mt-2 text-xs text-gray-600">
                        <div class="flex items-center gap-1"><i class="fas fa-user text-vesak-gold"></i> {c_gender}</div>
                        <div class="flex items-center gap-1"><i class="fas fa-birthday-cake text-vesak-gold"></i> {c_age} Yrs</div>
                    </div>
                </div>
                <div class="w-1/2 p-4 flex flex-col justify-center">
                    <div class="flex items-center gap-2 text-xs text-gray-600 mb-2">
                        <i class="fas fa-phone-alt text-vesak-gold w-4"></i> {c_mob}
                    </div>
                    <div class="flex items-start gap-2 text-xs text-gray-600">
                        <i class="fas fa-map-marker-alt text-vesak-gold w-4 mt-0.5"></i> 
                        <span class="leading-tight">{c_addr}</span>
                    </div>
                </div>
            </div>

            <table class="w-full mb-8">
                <thead>
                    <tr class="bg-vesak-navy text-white text-xs uppercase tracking-wider text-left">
                        <th class="p-3 w-3/5">Description</th>
                        <th class="p-3 w-2/5 text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="border-b border-gray-100">
                        <td class="p-4 align-top">
                            <div class="font-bold text-sm text-gray-800">{clean_plan}</div>
                            {desc_col_html}
                        </td>
                        <td class="p-4 text-right font-bold text-sm text-gray-800 align-top">
                            {amount_col_html}
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="grid grid-cols-2 gap-8">
                <div>
                    <h4 class="text-xs font-bold text-vesak-navy uppercase border-b border-vesak-gold pb-1 mb-3">Services Included</h4>
                    <ul class="list-disc pl-4 space-y-1">{inc_html}</ul>
                </div>
                <div>
                    <h4 class="text-xs font-bold text-gray-400 uppercase border-b border-gray-200 pb-1 mb-3">Services Not Included</h4>
                    <ul class="columns-1 text-[10px] text-gray-400 space-y-1">{exc_html}</ul>
                </div>
            </div>

            {notes_section}
            
        </main>

        <footer class="z-10">
            <div class="text-center text-xs text-gray-400 italic mb-4">
                Thank you for choosing Vesak Care Foundation!
            </div>
            <div class="w-full h-px bg-gradient-to-r from-gray-100 via-vesak-gold to-gray-100 opacity-50 mb-4"></div>
            <div class="flex justify-between items-end text-xs text-gray-500">
                <div>
                    <p class="font-serif italic text-vesak-navy mb-1 text-sm">Our Offices</p>
                    <div class="flex gap-2">
                        <span>Pune</span><span class="text-vesak-gold">•</span>
                        <span>Mumbai</span><span class="text-vesak-gold">•</span>
                        <span>Kolhapur</span>
                    </div>
                </div>

                <div class="flex items-center gap-6">
                    <a href="https://www.instagram.com/VesakCare/" target="_blank" class="flex items-center gap-2 text-gray-500 hover:text-vesak-gold transition-colors">
                        <i class="fab fa-instagram text-lg"></i>
                        <span>@VesakCare</span>
                    </a>
                    
                    <a href="https://www.facebook.com/VesakCare/" target="_blank" class="flex items-center gap-2 text-gray-500 hover:text-vesak-gold transition-colors">
                        <i class="fab fa-facebook text-lg"></i>
                        <span>@VesakCare</span>
                    </a>
                </div>
            </div>
            <div class="mt-4 w-full h-1 bg-vesak-navy"></div>              
        </footer>
    </div>

    <script>
        function generatePDF() {{
            const element = document.getElementById('invoice-content');
            const opt = {{
                margin: [0.5, 0.5, 0.5, 0.5],
                filename: '{preview_file_name}',
                image: {{ type: 'jpeg', quality: 1 }},
                html2canvas: {{ scale: 2, useCORS: true, letterRendering: true, scrollY: 0 }},
                jsPDF: {{ unit: 'mm', format: 'a4', orientation: 'portrait' }}
            }};
            html2pdf().set(opt).from(element).save();
        }}
    </script>
</body>
</html>
"""
    # Render preview in an iframe-like component
    st.markdown("### Live Preview")
    components = getattr(st, "components", None)
    if components is None:
        try:
            import streamlit.components.v1 as components
        except Exception:
            components = None

    if components:
        try:
            components.html(html_content, height=1100, scrolling=True)
        except Exception as e:
            st.error(f"Preview render failed: {e}")
    else:
        st.text_area("Invoice HTML Preview (copy/paste to file to view)", value=html_content, height=400)
